import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, Check, ChevronDown, Coins, Copy, Download, LoaderCircle, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import { Dropdown } from "@/components/dropdown";
import { useT, useUiLanguage } from "@/lib/i18n";
import { openUrl } from "@/lib/window";
import { loadTftCatalog } from "@/lib/games/tft";
import { decodeTftTeam, encodeTftTeam, readTftPlans, tftCounts, tftPlanKey, tftThresholds, tftTraitReference, type TftCatalog, type TftChampion, type TftPlans, type TftSet } from "@/lib/games/tft-data";
import { GameArt } from "./game-art";
import "./game-tft-companion.css";

function Portrait({ champion }: { champion: TftChampion }) {
  return <span className="games-tft-portrait"><span aria-hidden="true">{champion.name[0]}</span><GameArt src={champion.portrait} fallback={champion.icon}/><LoaderCircle size={19} aria-hidden="true"/></span>;
}
export function GameTftCompanion({ active, profile }: { active: boolean; profile: string }) {
  const t = useT(), language = useUiLanguage(), label = (key: string) => t(`games.tft.${key}`), root = useRef<HTMLElement>(null);
  const [visible, setVisible] = useState(false), [snapshot, setSnapshot] = useState<{ data: TftCatalog; at: number; language: string } | null>(null), [busy, setBusy] = useState(false), [failed, setFailed] = useState(false), [attempt, setAttempt] = useState(0), [selected, setSelected] = useState("");
  const [code, setCode] = useState(""), [importFailed, setImportFailed] = useState(false), [incoming, setIncoming] = useState<{ set: string; units: string[]; revision: number } | null>(null);
  useEffect(() => { if (!active || !root.current) return; const observer = new IntersectionObserver(entries => { if (entries.some(e => e.isIntersecting)) setVisible(true); }, { rootMargin: "200px" }); observer.observe(root.current); return () => observer.disconnect(); }, [active]);
  useEffect(() => {
    if (!active || !visible) return;
    const controller = new AbortController(); setBusy(true); setFailed(false);
    void loadTftCatalog(language, controller.signal, attempt > 0).then(value => { if (!controller.signal.aborted) setSnapshot({ ...value, language }); }, () => { if (!controller.signal.aborted) setFailed(true); }).finally(() => { if (!controller.signal.aborted) setBusy(false); });
    return () => controller.abort();
  }, [active, visible, language, attempt]);
  const catalog = snapshot?.language === language ? snapshot.data : null, set = catalog?.sets.find(s => s.id === selected) ?? catalog?.sets.find(s => s.id === catalog.defaultSet);
  return <section ref={root} className="games-tft" aria-label={label("title")}><header><div><p>TEAMFIGHT TACTICS</p><h2>{label("title")}</h2><span>{label("intro")}</span></div><div className="games-tft-source">{catalog && <span>{t("games.tft.version", { version: catalog.version })}</span>}<button className="games-button" disabled={busy} aria-label={label("refresh")} onClick={() => setAttempt(n => n + 1)}><RefreshCw size={17}/></button></div></header>
    {failed && <p role="status">{label(catalog ? "refreshFailed" : "loadFailed")} <button className="games-button" disabled={busy} onClick={() => setAttempt(n => n + 1)}>{t("common.retry")}</button></p>}
    {!catalog && !failed && <div className="games-tft-loading" role="status" aria-label={t("common.loading")}>{[0, 1, 2, 3, 4, 5].map(n => <i key={n}/>)}</div>}
    {catalog && set && <><div className="games-tft-catalog-tools">{active && <Dropdown ariaLabel={label("set")} value={set.id} options={catalog.sets.map(s => ({ value: s.id, label: `${s.name}${s.id === catalog.defaultSet ? ` · ${label("current")}` : ""}` }))} onChange={value => { setSelected(value); setIncoming(null); setImportFailed(false); }}/>}<form className="games-tft-import" onSubmit={event => { event.preventDefault(); try { const decoded = decodeTftTeam(code, catalog); setSelected(decoded.set.id); setIncoming({ set: decoded.set.id, units: decoded.units, revision: Date.now() }); setCode(""); setImportFailed(false); } catch { setImportFailed(true); } }}><input dir="ltr" aria-label={label("code")} placeholder={label("code")} value={code} maxLength={64} onChange={e => { setCode(e.target.value); setImportFailed(false); }} spellCheck={false}/><button className="games-button" disabled={!code.trim()} type="submit"><Download size={15}/>{label("import")}</button></form></div>
      {importFailed && <p role="alert">{label("invalidCode")}</p>}
      <TftPlanner key={`${profile}:${set.id}`} set={set} profile={profile} active={active} incoming={incoming?.set === set.id ? incoming : null}/>
      <footer><a href="https://www.communitydragon.org/" target="_blank" rel="noreferrer" onClick={e => { e.preventDefault(); void openUrl("https://www.communitydragon.org/"); }}>CommunityDragon<ArrowUpRight size={13}/></a><span>{t("games.tft.checked", { date: new Date(snapshot!.at).toLocaleString(language, { dateStyle: "short", timeStyle: "short" }) })}</span>{language.startsWith("hi") && <span>{label("english")}</span>}<span>Teamfight Tactics © Riot Games</span></footer>
    </>}
    <p className="games-tft-attribution">{t("games.league.attribution")}</p>
  </section>;
}
function TftPlanner({ set, profile, active, incoming }: { set: TftSet; profile: string; active: boolean; incoming: { units: string[]; revision: number } | null }) {
  const t = useT(), language = useUiLanguage(), label = (key: string) => t(`games.tft.${key}`), initial = useRef(readTftPlans(profile, set.id)), valid = (units: string[]) => units.filter(id => set.champions.some(c => c.id === id));
  const [plans, setPlans] = useState<TftPlans>({ ...initial.current, draft: valid(initial.current.draft) }), [missing, setMissing] = useState(valid(initial.current.draft).length !== initial.current.draft.length), [saveFailed, setSaveFailed] = useState(false);
  const [query, setQuery] = useState(""), [cost, setCost] = useState("all"), [traitId, setTraitId] = useState("all"), [name, setName] = useState(""), [teamId, setTeamId] = useState(""), [notice, setNotice] = useState("");
  const importRevision = useRef<number | null>(null);
  const persist = (next: TftPlans) => { setPlans(next); try { localStorage.setItem(tftPlanKey(profile, set.id), JSON.stringify(next)); setSaveFailed(false); } catch { setSaveFailed(true); } };
  useEffect(() => { if (incoming && incoming.revision !== importRevision.current) { importRevision.current = incoming.revision; persist({ ...plans, draft: incoming.units }); setMissing(false); setTeamId(""); setName(""); setNotice("imported"); } }, [incoming]);
  useEffect(() => { const draft = valid(plans.draft); if (draft.length !== plans.draft.length) { setPlans(previous => ({ ...previous, draft })); setMissing(true); } }, [set]);
  const counts = tftCounts(set, plans.draft), selected = plans.draft.flatMap(id => { const c = set.champions.find(c => c.id === id); return c ? [c] : []; }), traits = [...set.traits].sort((a, b) => (counts.get(b.id) ?? 0) - (counts.get(a.id) ?? 0) || a.name.localeCompare(b.name, language));
  const roster = set.champions.filter(c => (cost === "all" || c.cost === Number(cost)) && (traitId === "all" || c.traits.some(t => t.id === traitId)) && `${c.name} ${c.traits.map(t => set.traits.find(v => v.id === t.id)?.name ?? "").join(" ")}`.toLocaleLowerCase(language).includes(query.trim().toLocaleLowerCase(language))).sort((a, b) => a.cost - b.cost || a.name.localeCompare(b.name, language));
  function choose(id: string) { const has = plans.draft.includes(id); if (!has && plans.draft.length >= 10) { setNotice("full"); return; } persist({ ...plans, draft: has ? plans.draft.filter(v => v !== id) : [...plans.draft, id] }); setMissing(false); setNotice(""); }
  function load(id: string) { const saved = plans.teams.find(t => t.id === id); if (!saved) return; setTeamId(saved.id); setName(saved.name); const units = valid(saved.units); setMissing(units.length !== saved.units.length); persist({ ...plans, draft: units }); setNotice(""); }
  const save = () => { if (!name.trim() || !plans.draft.length) return; const id = teamId || `team_${Date.now()}`; if (!teamId && plans.teams.length >= 20) { setNotice("limit"); return; } const team = { id, name: name.trim(), units: plans.draft }; persist({ ...plans, teams: teamId ? plans.teams.map(t => t.id === teamId ? team : t) : [...plans.teams, team] }); setTeamId(id); setNotice("saved"); };
  return <><div className="games-tft-team"><div className="games-tft-team-heading"><h3>{label("yourTeam")}<span dir="ltr">{plans.draft.length} / 10</span></h3><div><button className="games-button" disabled={!selected.length} onClick={async () => { try { await navigator.clipboard.writeText(encodeTftTeam(set, plans.draft)); setNotice("copied"); } catch { setNotice("copyFailed"); } }}><Copy size={15}/>{label("copy")}</button><button className="games-button" onClick={() => { persist({ ...plans, draft: [] }); setName(""); setTeamId(""); setMissing(false); setNotice(""); }}><Plus size={15}/>{label("new")}</button></div></div>
    <div className="games-tft-slots">{selected.map(c => <button key={c.id} data-unit={c.id} data-cost={c.cost} aria-label={t("games.tft.remove", { name: c.name })} onClick={() => choose(c.id)}><Portrait champion={c}/><strong dir="auto">{c.name}</strong><X size={13}/></button>)}{Array.from({ length: 10 - selected.length }, (_, i) => <span className="games-tft-empty-slot" aria-hidden="true" key={i}><Plus size={18}/></span>)}</div>
    <div className="games-tft-save"><form onSubmit={e => { e.preventDefault(); save(); }}><input aria-label={label("name")} placeholder={label("name")} value={name} maxLength={60} onChange={e => setName(e.target.value)}/><button className="games-button" type="submit" disabled={!name.trim() || !selected.length}>{label("save")}</button></form>{active && plans.teams.length > 0 && <Dropdown ariaLabel={label("savedTeams")} value={teamId} placeholder={label("savedTeams")} options={plans.teams.map(t => ({ value: t.id, label: t.name }))} onChange={load}/>} {teamId && <button className="games-button" aria-label={label("delete")} onClick={() => { persist({ ...plans, teams: plans.teams.filter(t => t.id !== teamId) }); setTeamId(""); setName(""); setNotice(""); }}><Trash2 size={16}/></button>}</div>
    <p className="games-tft-note">{label("note")}</p><div role="status" className="games-tft-message">{saveFailed ? label("saveFailed") : notice ? label(notice) : ""}{missing && <span>{label("missing")}</span>}</div>
  </div>
  <div className="games-tft-workbench"><section className="games-tft-roster"><div className="games-tft-roster-tools"><label><Search size={16}/><input aria-label={label("search")} placeholder={label("search")} value={query} maxLength={100} onChange={e => setQuery(e.target.value)}/></label>{active && <Dropdown ariaLabel={label("cost")} value={cost} options={[{ value: "all", label: label("allCosts") }, ...[...new Set(set.champions.map(c => c.cost))].sort((a, b) => a - b).map(cost => ({ value: String(cost), label: t("games.tft.costValue", { count: cost }) }))]} onChange={setCost}/>}</div>
    {traitId !== "all" && <button className="games-tft-filter" onClick={() => setTraitId("all")} aria-label={label("clearFilter")}>{set.traits.find(t => t.id === traitId)?.name}<X size={14}/></button>}
    <div className="games-tft-roster-grid">{roster.map(c => <button key={c.id} data-unit={c.id} data-cost={c.cost} aria-pressed={plans.draft.includes(c.id)} aria-label={t("games.tft.champion", { name: c.name, cost: c.cost })} onClick={() => choose(c.id)}><Portrait champion={c}/><div><strong dir="auto">{c.name}</strong><span className="games-tft-cost" aria-hidden="true"><Coins size={11}/>{c.cost}</span></div><small dir="auto">{c.traits.map(v => set.traits.find(t => t.id === v.id)?.name).join(" · ")}</small>{plans.draft.includes(c.id) && <Check className="games-tft-selected" size={18}/>}</button>)}</div>{!roster.length && <p>{label("noResults")}</p>}
  </section><aside className="games-tft-traits"><h3>{label("traits")}</h3>{traits.filter(trait => counts.has(trait.id) || traitId === trait.id).map(trait => {
    const count = counts.get(trait.id) ?? 0, thresholds = tftThresholds(trait), reached = thresholds.filter(n => n <= count).at(-1), reference = tftTraitReference(trait, count, key => { const value = t(`games.tft.stat.${key}`); return value.startsWith("games.tft.stat.") ? "" : value; }), next = thresholds.find(n => n > count);
    return <details key={trait.id} data-trait={trait.id}><summary><GameArt src={trait.icon}/><span><strong dir="auto">{trait.name}</strong><small dir="ltr">{thresholds.join(" / ")}</small></span><b dir="ltr" data-active={!!reached}>{count}{next ? ` / ${next}` : ""}</b><ChevronDown size={14}/></summary><div className="games-tft-trait-reference">{reference.intro && <p>{reference.intro}</p>}{reference.levels.map((level, i) => level.text && <p key={i}>{level.text}</p>)}{reference.unresolved && <p className="games-tft-note">{label("unresolved")}</p>}<button className="games-button" aria-pressed={traitId === trait.id} onClick={() => setTraitId(traitId === trait.id ? "all" : trait.id)}>{label("showChampions")}</button></div></details>;
  })}{!selected.length && traitId === "all" && <p>{label("pickPrompt")}</p>}{active && <Dropdown menuClassName="games-tft-trait-menu" ariaLabel={label("browseTraits")} placeholder={label("browseTraits")} value={traitId} options={[{ value: "all", label: label("allTraits") }, ...[...set.traits].sort((a, b) => a.name.localeCompare(b.name, language)).map(t => ({ value: t.id, label: t.name, left: <GameArt src={t.icon}/> }))]} onChange={setTraitId}/>}</aside></div></>;
}
