import {useEffect,useId,useMemo,useRef,useState} from "react";
import {ArrowLeft,Check,FolderPlus,MoreHorizontal,Pin,Plus,Search,X} from "lucide-react";
import {ModalShell,useModalExit} from "@/components/modal-shell";
import {Dropdown} from "@/components/dropdown";
import {useSectionBack} from "@/lib/section-back";
import {useT} from "@/lib/i18n";
import {collectionHasGame,type PersonalGameCollection,type PersonalCollectionGame} from "@/lib/games/personal-collections";
import {defaultCollectionRules,type CollectionRules} from "@/lib/games/collection-rules";
import {dynamicCollectionGames} from "@/lib/games/dynamic-collections";
import {normalizeLibraryQuery,type UnifiedLibraryGame} from "@/lib/games/unified-library";
import {CollectionRuleSummary,GameCollectionRules} from "./game-collection-rules";
import type {GameSummary} from "@/lib/games/types";
import type {PersonalGameCollectionsState} from "@/hooks/use-personal-game-collections";
import {resolveCollectionLibrary} from "@/lib/games/personal-collection-library";
import {GameCollectionLocalCard, localCollectionArtwork, type CollectionLibraryAccess} from "./game-collection-local-card";
import {LibrarySourceMark} from "./game-library-marks";
import {GameArt} from "./game-art";
import {GameCard} from "./game-ui";
import "./game-personal-collections.css";

function CollectionCover({collection,state,artwork,members}:{collection:PersonalGameCollection;state:PersonalGameCollectionsState;artwork?:(game:PersonalCollectionGame)=>string|undefined;members?:PersonalCollectionGame[]}){
 const games=(members??collection.gameIds.map(id=>state.data.games[id])).slice(0,4);
 return <span className={`games-personal-cover games-personal-cover-${games.length}`} aria-hidden="true">{games.length?games.map(game=>{const src=artwork?.(game)||game.portrait||game.capsule;return src?<GameArt key={game.id} src={src}/>:<span className="games-personal-cover-name" key={game.id}><LibrarySourceMark source={game.local?.kind==="rom"?"retro":"custom"} size={22}/><span>{game.name}</span></span>;}):<LibrarySourceMark source="collections" size={35}/>}</span>;
}
function CollectionError({state}:{state:PersonalGameCollectionsState}){const t=useT();return state.error?<div className="games-personal-error" role="alert"><p>{t(`games.collections.${["collections_name","collections_duplicate","collections_limit","collections_missing","collections_game","collections_read","collections_rules","collections_dynamic"].includes(state.error)?state.error:"collections_write"}`)}</p>{!state.ready?<button className="games-button" onClick={state.reload}>{t("common.retry")}</button>:<button className="games-icon-button" aria-label={t("common.close")} onClick={state.dismissError}><X size={16}/></button>}</div>:null;}

export function GameCollectionPicker({game,state,onClose}:{game:PersonalCollectionGame|PersonalCollectionGame[];state:PersonalGameCollectionsState;onClose:()=>void}){
 const t=useT(),titleId=useId(),root=useRef<HTMLDivElement>(null),search=useRef<HTMLInputElement>(null);
 const batch=Array.isArray(game),games=batch?game:[game],contains=(c:PersonalGameCollection)=>games.every(value=>collectionHasGame(state.data,c,value));
 const[query,setQuery]=useState(""),[name,setName]=useState("");const{closing,close}=useModalExit(onClose);
 useSectionBack(close,true);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;search.current?.focus({preventScroll:true});const dialog=root.current?.closest('[role="dialog"]');const trap=(e:KeyboardEvent)=>{if(e.key!=="Tab"||!dialog)return;const all=[...dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled)')].filter(el=>el.getClientRects().length);if(e.shiftKey&&(document.activeElement===all[0]||!dialog.contains(document.activeElement))){e.preventDefault();all.at(-1)?.focus();}else if(!e.shiftKey&&(document.activeElement===all.at(-1)||!dialog.contains(document.activeElement))){e.preventDefault();all[0]?.focus();}};document.addEventListener("keydown",trap);return()=>{document.removeEventListener("keydown",trap);if(previous?.isConnected)previous.focus({preventScroll:true});};},[]);
 const list=[...state.data.collections].filter(c=>!c.rules).filter(c=>normalizeLibraryQuery(c.name).includes(normalizeLibraryQuery(query))).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updatedAt-a.updatedAt);
 const toggle=async(c:PersonalGameCollection)=>{if(batch){await state.addMany(c.id,games);}else if(collectionHasGame(state.data,c,game)){const id=c.gameIds.find(id=>collectionHasGame(state.data,{...c,gameIds:[id]},game));if(id)await state.removeGame(c.id,id);}else await state.add(c.id,game);};
 const create=async()=>{if(await (batch?state.createMany(name,games):state.create(name,game))){setName("");setQuery("");search.current?.focus({preventScroll:true});}};
 return <ModalShell closing={closing} onDismiss={close} width={480} labelledBy={titleId} backdropClassName="games-personal-backdrop"><div className="games-personal-picker" ref={root}>
  <header><span><p className="games-section-kicker">{t("games.collections.addTo")}</p><h2 id={titleId}>{batch?t("games.selection.count",{count:games.length}):game.name}</h2></span><button className="games-icon-button" onClick={close} aria-label={t("common.close")}><X size={19}/></button></header>
  <div className="games-search"><Search size={16}/><input ref={search} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("games.collections.search")} aria-label={t("games.collections.search")}/>{query&&<button className="games-icon-button" aria-label={t("games.clear")} onClick={()=>setQuery("")}><X size={15}/></button>}</div>
  <div className="games-personal-picker-list">{list.map(c=><button key={c.id} aria-pressed={contains(c)} disabled={state.busy||!state.ready||(batch&&contains(c))} onClick={()=>void toggle(c)}><CollectionCover collection={c} state={state}/><span><strong>{c.name}</strong><small>{t(c.gameIds.length===1?"games.collections.one":"games.collections.count",{count:c.gameIds.length})}</small></span>{contains(c)?<Check size={18}/>:<Plus size={18}/>}</button>)}{state.ready&&!list.length&&<p className="games-personal-picker-empty">{t(query||state.data.collections.length?"games.collections.noMatches":"games.collections.first")}</p>}</div>
  <CollectionError state={state}/>
  <form onSubmit={e=>{e.preventDefault();void create();}}><label className="sr-only" htmlFor={`${titleId}-new`}>{t("games.collections.name")}</label><input id={`${titleId}-new`} maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder={t("games.collections.newName")}/><button className="games-button" disabled={!name.trim()||state.busy||!state.ready}><FolderPlus size={17}/>{t("games.collections.create")}</button></form>
  <footer><span>{t("games.collections.pickerNote")}{state.data.collections.some(c=>c.rules)&&<> {t("games.collections.pickerAutoNote")}</>}</span><button className="games-button games-button-primary" onClick={close}>{t("games.collections.done")}</button></footer>
 </div></ModalShell>;
}

export function GamePersonalCollections({state,query,active,open,addGames,library,onQueryChange,unified=[],libraryPending=false,libraryPartial=false}:{state:PersonalGameCollectionsState;query:string;active:boolean;open:(game:GameSummary)=>void;addGames:()=>void;library:CollectionLibraryAccess;onQueryChange:(query:string)=>void;unified?:UnifiedLibraryGame[];libraryPending?:boolean;libraryPartial?:boolean}){
 const t=useT(),root=useRef<HTMLElement>(null),[selected,setSelected]=useState<string|null>(null),[name,setName]=useState(""),[editing,setEditing]=useState(false),[description,setDescription]=useState(""),[confirm,setConfirm]=useState(false),[limit,setLimit]=useState(36),[sort,setSort]=useState("added");
 const [dynamic,setDynamic]=useState(false),[rules,setRules]=useState<CollectionRules>(defaultCollectionRules);
 const members=useMemo(()=>Object.fromEntries(state.data.collections.map(c=>[c.id,c.rules?dynamicCollectionGames(c.rules,unified):c.gameIds.map(id=>state.data.games[id])])),[state.data,unified]);
 const resolved=useMemo(()=>resolveCollectionLibrary(Object.values(members).flat(),library.customLibrary.data.games,library.emulation.data),[members,library.customLibrary.data.games,library.emulation.data]);
 const draftCount=useMemo(()=>dynamicCollectionGames(rules,unified).length,[rules,unified]);
 const artwork=(game:PersonalCollectionGame)=>game.local?localCollectionArtwork(resolved[game.id],library.preferences):game.portrait||game.capsule;
 const focusTitle=()=>requestAnimationFrame(()=>root.current?.querySelector<HTMLElement>("[data-personal-title]")?.focus({preventScroll:true}));
 const previous=useRef<{id:string;top:number;query:string}|null>(null);const selectedCollection=state.data.collections.find(c=>c.id===selected);
 const back=()=>{onQueryChange(previous.current?.query??"");setSelected(null);setEditing(false);setConfirm(false);setName("");requestAnimationFrame(()=>{const target=previous.current;if(target){root.current?.closest('.games-view')?.scrollTo({top:target.top,behavior:"instant"});root.current?.querySelector<HTMLElement>(`[data-personal-collection="${target.id}"]`)?.focus({preventScroll:true});}});};
 const closeEditor=()=>{setEditing(false);setConfirm(false);setName("");requestAnimationFrame(()=>root.current?.querySelector<HTMLElement>("[data-collection-edit]")?.focus({preventScroll:true}));};
 useSectionBack(()=>editing?closeEditor():back(),active&&selected!==null);
 useEffect(()=>{if(selected&&!selectedCollection&&state.ready)back();},[selected,selectedCollection,state.ready]);
 useEffect(()=>setLimit(36),[query,selected,sort]);
 useEffect(()=>{if(!active){setConfirm(false);setEditing(false);}},[active]);
 const collections=[...state.data.collections].filter(c=>normalizeLibraryQuery(c.name).includes(normalizeLibraryQuery(query))).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updatedAt-a.updatedAt);
 const games=(selectedCollection?members[selectedCollection.id]:[])?.map(game=>resolved[game.id].game).filter(game=>normalizeLibraryQuery(game.name).includes(normalizeLibraryQuery(query)))??[];
 if(sort==="name")games.sort((a,b)=>a.name.localeCompare(b.name));
 const create=async()=>{const id=await (dynamic?state.createDynamic(name,rules):state.create(name));if(id){previous.current={id,top:root.current?.closest('.games-view')?.scrollTop??0,query};onQueryChange("");setName("");setSelected(id);focusTitle();}};
 const edit=()=>{if(!selectedCollection)return;setName(selectedCollection.name);setDescription(selectedCollection.description);setRules(selectedCollection.rules??defaultCollectionRules());setEditing(true);setConfirm(false);};
 const save=async()=>{if(selectedCollection&&await state.update(selectedCollection.id,{name,description,...(selectedCollection.rules?{rules}:{})})){closeEditor();}};
 const remove=async()=>{if(selectedCollection&&await state.remove(selectedCollection.id))back();};
 return <section className="games-personal-collections games-inset" ref={root}>
  {selectedCollection?<><button className="games-button games-personal-back" onClick={back}><ArrowLeft size={17}/>{t("games.collections.title")}</button><header className="games-personal-detail-heading"><CollectionCover collection={selectedCollection} state={state} artwork={artwork} members={members[selectedCollection.id]}/><div><p className="games-eyebrow">{t(selectedCollection.rules?"games.collections.dynamic":"games.collections.personal")}</p><h2 tabIndex={-1} data-personal-title>{selectedCollection.name}</h2>{selectedCollection.description&&<p>{selectedCollection.description}</p>}<span>{t(members[selectedCollection.id].length===1?"games.collections.one":"games.collections.count",{count:members[selectedCollection.id].length})}</span></div><button data-collection-edit className="games-icon-button" title={t("games.collections.edit")} aria-label={t("games.collections.edit")} aria-expanded={editing} onClick={()=>editing?closeEditor():edit()}><MoreHorizontal size={21}/></button></header>
   {editing&&<form className="games-personal-edit" onSubmit={e=>{e.preventDefault();void save();}}><label>{t("games.collections.name")}<input autoFocus maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t("games.collections.description")}<textarea maxLength={240} rows={2} value={description} onChange={e=>setDescription(e.target.value)}/></label>{selectedCollection.rules&&<><GameCollectionRules rules={rules} onChange={setRules}/><p className="games-collection-rule-note" role="status">{t("games.collections.matches",{count:draftCount})}</p></>}<div><button className="games-button" type="button" aria-pressed={selectedCollection.pinned} disabled={state.busy} onClick={()=>void state.update(selectedCollection.id,{pinned:!selectedCollection.pinned})}><Pin size={15}/>{t(selectedCollection.pinned?"games.collections.unpin":"games.collections.pin")}</button><button className="games-button" type="button" onClick={()=>setConfirm(!confirm)}>{t("games.collections.remove")}</button><button type="button" className="games-button" onClick={closeEditor}>{t("common.cancel")}</button><button className="games-button games-button-primary" disabled={!name.trim()||state.busy}>{t("games.collections.save")}</button></div>{confirm&&<div className="games-personal-confirm"><p>{t("games.collections.removeNote")}</p><button type="button" className="games-button" disabled={state.busy} onClick={()=>void remove()}>{t("games.collections.confirmRemove")}</button></div>}</form>}
   {selectedCollection.rules&&<><CollectionRuleSummary rules={selectedCollection.rules}/><p className="games-collection-rule-note">{t("games.collections.autoNote")}{libraryPending?<> {t("common.loading")}</>:libraryPartial?<> {t("games.unified.partial")}</>:null}</p></>}
   <div className="games-personal-toolbar"><span>{t(games.length===1?"games.collections.one":"games.collections.count",{count:games.length})}</span><Dropdown value={sort} onChange={setSort} ariaLabel={t("games.library.sort")} size="sm" options={[{value:"added",label:t(selectedCollection.rules?"games.dock.recentSort":"games.collections.added")},{value:"name",label:t("games.library.sort.name")}]}/></div>
   {games.length?<div className="games-grid games-personal-games">{games.slice(0,limit).map(game=><div key={game.id}>{game.local?<GameCollectionLocalCard entry={resolved[game.id]} access={library} active={active} open={open}/>:<GameCard game={game} open={open}/>}{!selectedCollection.rules&&<button className="games-personal-remove-game" disabled={state.busy} onClick={()=>void state.removeGame(selectedCollection.id,game.id)} aria-label={t("games.collections.removeGame",{name:game.name})}><X size={14}/>{t("games.collections.removeShort")}</button>}</div>)}</div>:<div className="games-personal-empty"><LibrarySourceMark source="collections" size={31}/><h3>{t(query||selectedCollection.rules?"games.noResults":"games.collections.empty")}</h3><p>{t(query?"games.trySearch":selectedCollection.rules?"games.collections.emptyDynamic":"games.collections.emptyNote")}</p>{!query&&<button className="games-button" onClick={selectedCollection.rules?edit:addGames}>{t(selectedCollection.rules?"games.collections.filters":"games.collections.findGames")}</button>}</div>}
   {games.length>limit&&<button className="games-button games-library-more" onClick={()=>setLimit(n=>n+36)}>{t("games.library.showMore")}</button>}
  </>:<><div className="games-section-heading"><div><p className="games-eyebrow">{t("games.collections.personal")}</p><h2>{t("games.collections.title")}</h2></div><LibrarySourceMark source="collections" size={28}/></div><form className="games-personal-create" onSubmit={e=>{e.preventDefault();void create();}}><div className="games-personal-create-type"><Dropdown value={dynamic?"dynamic":"manual"} onChange={value=>setDynamic(value==="dynamic")} ariaLabel={t("games.collections.type")} options={[{value:"manual",label:t("games.collections.manual")},{value:"dynamic",label:t("games.collections.dynamic")}]}/></div><input aria-label={t("games.collections.name")} maxLength={80} placeholder={t("games.collections.newName")} value={name} onChange={e=>setName(e.target.value)}/><button className="games-button" disabled={!name.trim()||state.busy||!state.ready}><Plus size={17}/>{t("games.collections.create")}</button>{dynamic&&<div className="games-personal-create-rules"><GameCollectionRules rules={rules} onChange={setRules}/><p className="games-collection-rule-note">{t("games.collections.autoNote")}</p><p className="games-collection-rule-note" role="status">{t("games.collections.matches",{count:draftCount})}{libraryPending?<> {t("common.loading")}</>:libraryPartial?<> {t("games.unified.partial")}</>:null}</p></div>}</form>
   <div className="games-personal-grid">{collections.map(c=><button key={c.id} className="games-personal-tile" data-personal-collection={c.id} onClick={()=>{previous.current={id:c.id,top:root.current?.closest(".games-view")?.scrollTop??0,query};onQueryChange("");setSelected(c.id);setName("");focusTitle();root.current?.scrollIntoView({block:"start",behavior:"instant"});}}><CollectionCover collection={c} state={state} artwork={artwork} members={members[c.id]}/><span><strong>{c.name}{c.pinned&&<Pin size={14}/>}</strong><small>{t(members[c.id].length===1?"games.collections.one":"games.collections.count",{count:members[c.id].length})}{c.rules&&<> · {t("games.collections.dynamic")}</>}</small></span></button>)}</div>
   {state.ready&&!collections.length&&!dynamic&&<div className="games-personal-empty"><LibrarySourceMark source="collections" size={34}/><h3>{t(query?"games.collections.noMatches":"games.collections.first")}</h3><p>{t("games.collections.firstNote")}</p></div>}
  </>}
  <CollectionError state={state}/>
  {(library.customLibrary.error||library.emulation.error)&&<div className="games-personal-error" role="alert"><p>{t(library.customLibrary.error||library.emulation.error)}</p><button className="games-icon-button" aria-label={t("common.close")} onClick={()=>{library.customLibrary.dismissError();library.emulation.dismissError();}}><X size={16}/></button></div>}
 </section>;
}
