import { useState } from "react";
import { ArrowRight, RefreshCw } from "lucide-react";
import { useT } from "@/lib/i18n";
import { Dropdown } from "@/components/dropdown";
import { loadLeagueTiers, loadLeagueVersions } from "@/lib/games/league";
import { leagueDisplayPatch, LEAGUE_ROLES, normalizeChampion, roleIcon, type LeagueChampion, type LeagueRole } from "@/lib/games/league-data";
import { GameArt } from "./game-art";
import { LeagueLink, LeagueStatus } from "./game-league-companion";
import { useLeagueFeed } from "./use-league-feed";

export function LeagueTierList({ active, champions, query, language, choose }: { active: boolean; champions: LeagueChampion[]; query: string; language: string; choose: (champion: LeagueChampion, role: LeagueRole) => void }) {
  const t = useT(), [attempt, setAttempt] = useState(0), [chosenPatch, setPatch] = useState(""), [role, setRole] = useState("all"), [sort, setSort] = useState("tier"), [limit, setLimit] = useState(20);
  const versions = useLeagueFeed("league-patches", active, attempt, loadLeagueVersions), patch = chosenPatch || versions.data?.[0] || "";
  const feed = useLeagueFeed(`league-tier:${patch}`, active && !!patch, attempt, (signal, refresh) => loadLeagueTiers(patch, signal, refresh));
  const rows = (feed.data?.rows ?? []).flatMap(row => { const champion = champions.find(c => c.id === row.id); return champion ? [{ ...row, champion }] : []; }).filter(row => (role === "all" || row.role === role) && normalizeChampion(`${row.champion.name} ${row.champion.key}`).includes(normalizeChampion(query))).sort((a, b) => sort === "win" ? b.winRate - a.winRate : sort === "picks" ? b.pickRate - a.pickRate : a.tier - b.tier || a.rank - b.rank || b.games - a.games);
  const percent = new Intl.NumberFormat(language, { style: "percent", maximumFractionDigits: 1 }), number = new Intl.NumberFormat(language);
  return <section className="league-tier-list" aria-label={t("games.league.tierList")}>
    <header><div><h3>{t("games.league.tierList")}</h3><p>{t("games.league.tierScope")}</p></div><button className="games-icon-button" aria-label={t("games.league.refresh")} disabled={feed.busy || versions.busy} onClick={() => setAttempt(n => n + 1)}><RefreshCw size={17}/></button></header>
    <div className="league-tier-filters"><Dropdown value={patch} ariaLabel={t("games.league.patchFilter")} options={(versions.data ?? []).map(v => ({ value: v, label: t("games.league.patch", { patch: leagueDisplayPatch(v) }) }))} onChange={v => { setPatch(v); setLimit(20); }}/><Dropdown value={role} ariaLabel={t("games.league.role")} options={[{ value: "all", label: t("games.league.allRoles") }, ...LEAGUE_ROLES.map(v => ({ value: v, label: t(`games.league.role.${v}`), left: <img className="league-role-icon" alt="" src={roleIcon(v)}/> }))]} onChange={v => { setRole(v); setLimit(20); }}/><Dropdown value={sort} ariaLabel={t("games.league.sort")} options={["tier", "win", "picks"].map(v => ({ value: v, label: t(`games.league.sort.${v}`) }))} onChange={setSort}/></div>
    <LeagueStatus failed={feed.failed || versions.failed} busy={feed.busy || versions.busy} retry={() => setAttempt(n => n + 1)}/>
    {feed.data && <><p className="league-tier-summary">{t("games.league.patch", { patch: leagueDisplayPatch(feed.data.patch) })}<span>{t("games.league.games", { count: number.format(feed.data.matches) })}</span></p><div className="league-tier-table"><div className="league-tier-table-heading" aria-hidden="true"><span>{t("games.league.champion")}</span><span>{t("games.league.role")}</span><span>{t("games.league.tierList")}</span><span>{t("games.league.winRate")}</span><span>{t("games.league.pickRate")}</span><span>{t("games.league.banRate")}</span><span>{t("games.league.matches")}</span></div>{rows.slice(0, limit).map(item => <button key={`${item.id}:${item.role}`} onClick={() => choose(item.champion, item.role)}><span className="league-tier-identity"><GameArt src={item.champion.portrait}/><strong>{item.champion.name}</strong></span><span className="league-tier-role"><GameArt src={roleIcon(item.role)}/><small>{t(`games.league.role.${item.role}`)}</small></span><b className="league-tier-grade">{item.tier === 0 ? "OP" : t("games.league.tier", { tier: item.tier })}</b><span>{percent.format(item.winRate)}</span><span>{percent.format(item.pickRate)}</span><span>{percent.format(item.banRate)}</span><span>{number.format(item.games)}</span></button>)}</div>{!rows.length && <p className="league-status">{t("games.league.empty")}</p>}{rows.length > limit && <button className="games-button league-more" onClick={() => setLimit(n => n + 20)}>{t("games.league.more")}<ArrowRight size={15}/></button>}<footer className="league-source"><span>{t("games.league.updated", { date: new Date(feed.data.at).toLocaleString(language, { dateStyle: "medium", timeStyle: "short" }) })}</span><LeagueLink href={`https://op.gg/lol/champions?region=global&tier=emerald_plus&version=${encodeURIComponent(patch)}`}>OP.GG</LeagueLink><LeagueLink href="https://u.gg/lol/tier-list">U.GG</LeagueLink><p>{t("games.league.tierNote")}</p></footer></>}
  </section>;
}
