import { leagueDisplayPatch } from "@/lib/games/league-data";
import { Play } from "@/components/icons/play-filled";
import { useState } from "react";
import { ArrowRight, Heart } from "lucide-react";
import { useT } from "@/lib/i18n";
import { Dropdown } from "@/components/dropdown";
import { HoverTooltip } from "@/components/hover-tooltip";
import { loadLeagueAssets, loadLeagueBuild, loadLeagueKit } from "@/lib/games/league";
import { DRAGON, LEAGUE_ROLES, roleIcon, type LeagueAssets, type LeagueBuildGroup, type LeagueChampion, type LeagueCounter, type LeagueRole } from "@/lib/games/league-data";
import { GameArt } from "./game-art";
import { useHackVideo } from "./game-hack-video";
import { LeagueLink, LeagueStatus } from "./game-league-companion";
import { useLeagueFeed } from "./use-league-feed";

export function LeagueChampionView({ champion, champions, patch, language, active, role, setRole, saved, save, choose }: {
  champion: LeagueChampion; champions: LeagueChampion[]; patch: string; language: string; active: boolean; role: LeagueRole; setRole: (role: LeagueRole) => void; saved: boolean; save: () => void; choose: (champion: LeagueChampion) => void;
}) {
  const t = useT(), watch = useHackVideo(), [tab, setTab] = useState("build"), [attempt, setAttempt] = useState(0), [ability, setAbility] = useState("P"), [skin, setSkin] = useState(0);
  const kit = useLeagueFeed(`kit:${champion.id}:${patch}:${language}`, active, attempt, signal => loadLeagueKit(champion, patch, language, signal));
  const build = useLeagueFeed(`build:${champion.id}:${role}`, active && tab === "build", attempt, (signal, refresh) => loadLeagueBuild(champion, role, signal, refresh));
  const items = useLeagueFeed(`items:${patch}:${language}`, active && tab === "build", attempt, signal => loadLeagueAssets(patch, language, "item", signal));
  const spells = useLeagueFeed(`spells:${patch}:${language}`, active && tab === "build", attempt, signal => loadLeagueAssets(patch, language, "spell", signal));
  const runes = useLeagueFeed(`runes:${patch}:${language}`, active && tab === "build", attempt, signal => loadLeagueAssets(patch, language, "rune", signal));
  const data = build.data, selectedAbility = kit.data?.abilities.find(a => a.key === ability), selectedSkin = kit.data?.skins[skin];
  const numeric = new Intl.NumberFormat(language), percent = new Intl.NumberFormat(language, { style: "percent", maximumFractionDigits: 1 });
  const urlKey = champion.key === "MonkeyKing" ? "wukong" : champion.key.toLowerCase();
  const Group = ({ group, assets, title }: { group: LeagueBuildGroup | null; assets: LeagueAssets | null; title: string }) => group && <div className="league-build-group"><h4>{title}</h4><div className="league-build-icons">{group.ids.map((id, index) => <div key={`${id}:${index}`} className="league-build-icon"><HoverTooltip label={assets?.[id]?.description || assets?.[id]?.name || String(id)}><span tabIndex={0}><GameArt src={assets?.[id]?.image ?? ""} alt={assets?.[id]?.name ?? String(id)}/></span></HoverTooltip><span>{assets?.[id]?.name ?? `#${id}`}</span>{index < group.ids.length - 1 && title === t("games.league.core") && <ArrowRight size={13}/>}</div>)}</div><p className="league-build-sample"><b>{percent.format(group.wins / group.games)}</b> {t("games.league.winRate")}<span>· {t("games.league.games", { count: numeric.format(group.games) })}</span></p></div>;
  const Counters = ({ counters, title }: { counters: LeagueCounter[]; title: string }) => <div className="league-counters"><h4>{title}</h4><p>{t("games.league.matchupRate", { champion: champion.name })}</p>{counters.length ? counters.map(counter => { const opponent = champions.find(c => c.id === counter.id); return <button key={counter.id} disabled={!opponent} onClick={() => opponent && choose(opponent)}><GameArt src={opponent?.portrait ?? ""}/><span><strong>{opponent?.name ?? counter.name}</strong><small>{t("games.league.games", { count: numeric.format(counter.games) })}</small></span><b>{percent.format(counter.winRate)}</b></button>; }) : <p>{t("games.league.noSample")}</p>}</div>;
  return <>
    <div className="league-champion-hero"><GameArt eager src={champion.splash} fallback={champion.portrait}/><div className="league-champion-copy"><p className="league-eyebrow">{champion.title}</p><h2 className="league-champion-title" tabIndex={-1}>{champion.name}</h2><p>{champion.tags.join(" · ")}</p><button className="league-save" aria-pressed={saved} onClick={save}><Heart size={19} fill={saved ? "currentColor" : "none"}/>{t(saved ? "games.league.inPool" : "games.league.addPool")}</button></div></div>
    <div className="league-toolbar league-champion-toolbar"><div className="league-tabs" role="group" aria-label={t("games.league.championSections")}>{["build", "abilities", "skins"].map(value => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)}>{t(`games.league.${value}`)}</button>)}</div>{tab === "build" && <Dropdown ariaLabel={t("games.league.role")} value={role} onChange={v => setRole(v as LeagueRole)} options={LEAGUE_ROLES.map(v => ({ value: v, label: t(`games.league.role.${v}`), left: <img className="league-role-icon" src={roleIcon(v)} alt=""/> }))}/>}</div>
    {tab === "build" && <>
      <div className="league-build-heading"><div><h3>{t("games.league.buildTitle")}</h3><p>{t("games.league.buildScope")}{data?.patch && ` · ${t("games.league.patch", { patch: leagueDisplayPatch(data.patch) })}`}</p></div><LeagueLink href={`https://op.gg/lol/champions/${urlKey}/build/${role}?tier=all`}>OP.GG</LeagueLink></div>
      <LeagueStatus failed={build.failed} busy={build.busy} retry={() => setAttempt(v => v + 1)}/>
      {data && <>
        {data.patch && !patch.startsWith(`${data.patch}.`) && patch !== data.patch && <p className="league-status">{t("games.league.patchDifference", { patch: leagueDisplayPatch(data.patch), assets: patch })}</p>}
        <div className="league-build-layout"><div className="league-build-main">
          <div className="league-core"><Group title={t("games.league.core")} group={data.core} assets={items.data}/></div>
          <div className="league-build-essentials"><Group title={t("games.league.start")} group={data.start} assets={items.data}/><Group title={t("games.league.boots")} group={data.boots} assets={items.data}/><Group title={t("games.league.spells")} group={data.spells} assets={spells.data}/></div>
          <div className="league-runes"><Group title={t("games.league.runes")} group={data.runes} assets={runes.data}/></div>
          {(items.failed || spells.failed || runes.failed) && <p className="league-status">{t("games.league.iconsUnavailable")}</p>}
          {data.skillMax.length > 0 && <div className="league-skill-order"><h4>{t("games.league.skillPriority")}</h4><div>{data.skillMax.map((key, index) => <span key={key}><GameArt src={kit.data?.abilities.find(a => a.key === key)?.image ?? ""}/><b>{key}</b>{index < data.skillMax.length - 1 && <Chevron/>}</span>)}</div>{data.skillOrder.length > 0 && <ol aria-label={t("games.league.skillOrder")}>{data.skillOrder.map((key, index) => <li key={index}><small>{index + 1}</small><b>{key}</b></li>)}</ol>}</div>}
        </div><aside className="league-matchups"><Counters counters={data.weak} title={t("games.league.weak")}/><Counters counters={data.strong} title={t("games.league.strong")}/></aside></div>
        {data.videos.length > 0 && <section className="league-videos"><header><div><h3>{t("games.league.combos")}</h3><p>{t("games.league.combosIntro")}</p></div></header><div>{data.videos.slice(0, 4).map(video => <button key={video.id} onClick={() => watch({ id: video.id, title: `${champion.name} · ${video.name}`, gameName: "League of Legends", gameId: 115 })}><div><GameArt src={`https://i.ytimg.com/vi/${video.id}/hqdefault.jpg`}/><span><Play size={22}/></span></div><strong>{video.name}</strong><small>{t("games.league.watchCombo")}</small></button>)}</div></section>}
        <footer className="league-source"><span>OP.GG</span>{data.sourceAt > 0 && <span>{t("games.league.updated", { date: new Date(data.sourceAt).toLocaleString(language, { dateStyle: "medium", timeStyle: "short" }) })}</span>}<details><summary>{t("games.league.aboutData")}</summary><p>{t("games.league.buildNote")}</p></details></footer>
      </>}
      {!data && !build.busy && <p className="league-status">{t("games.league.buildEmpty")}</p>}
    </>}
    {tab === "abilities" && <><LeagueStatus failed={kit.failed} busy={kit.busy} retry={() => { setAttempt(v => v + 1); }}/>{kit.data && <><div className="league-kit"><div className="league-ability-list" role="group" aria-label={t("games.league.abilities")}>{kit.data.abilities.map(a => <button key={a.key} aria-pressed={ability === a.key} onClick={() => setAbility(a.key)}><GameArt src={a.image}/><kbd>{a.key}</kbd><span>{a.name}</span></button>)}</div>{selectedAbility && <article className="league-ability-description"><div><GameArt src={selectedAbility.image}/><span><small>{selectedAbility.key === "P" ? t("games.league.passive") : selectedAbility.key}</small><h3>{selectedAbility.name}</h3></span></div><p>{selectedAbility.description}</p>{selectedAbility.cooldown && <small>{t("games.league.cooldown", { seconds: selectedAbility.cooldown })}</small>}</article>}</div><div className="league-tips">{[["allyTips", kit.data.tips], ["enemyTips", kit.data.enemyTips]].map(([key, tips]) => (tips as string[]).length > 0 && <div key={key as string}><h3>{t(`games.league.${key}`)}</h3><ul>{(tips as string[]).map(tip => <li key={tip}>{tip}</li>)}</ul></div>)}</div><details className="league-lore"><summary>{t("games.league.story")}</summary><p>{kit.data.lore}</p></details><p className="league-source">Riot Games · {t("games.league.patch", { patch: leagueDisplayPatch(patch) })}</p></>}</>}
    {tab === "skins" && <><LeagueStatus failed={kit.failed} busy={kit.busy} retry={() => setAttempt(v => v + 1)}/>{selectedSkin && <><div className="league-skin-stage"><GameArt key={selectedSkin.num} src={`${DRAGON}/cdn/img/champion/splash/${champion.key}_${selectedSkin.num}.jpg`}/><div><h3>{selectedSkin.num === 0 ? champion.name : selectedSkin.name}</h3><span>{skin + 1} / {kit.data?.skins.length}</span></div></div><div className="league-skin-picker" aria-label={t("games.league.skins")}>{kit.data?.skins.map((s, index) => <button key={s.num} aria-pressed={skin === index} onClick={() => setSkin(index)}><GameArt src={`${DRAGON}/cdn/img/champion/loading/${champion.key}_${s.num}.jpg`}/><span>{s.num === 0 ? champion.name : s.name}</span></button>)}</div></>}</>}
    <div className="league-resources"><span>{t("games.league.exploreMore")}</span><LeagueLink href={`https://u.gg/lol/champions/${urlKey}/build`}>U.GG</LeagueLink><LeagueLink href={`https://lolalytics.com/lol/${urlKey}/build/`}>LoLalytics</LeagueLink><LeagueLink href={`https://www.youtube.com/results?search_query=${encodeURIComponent(`${champion.name} ${role} guide League of Legends`)}`}>{t("games.league.guides")}</LeagueLink></div>
  </>;
}
function Chevron() { return <ArrowRight size={15}/>; }
