import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../domain/catalog/catalog_row.dart';
import '../domain/stremboxd/letterboxd_home_rows.dart';
import '../domain/stremboxd/letterboxd_reviews.dart';
import '../domain/stremboxd/letterboxd_session_store.dart';
import '../domain/stremboxd/stremboxd_client.dart';
import 'iptv_providers.dart' show textTransportProvider;
import 'providers.dart';

/// The Stremboxd client behind the Letterboxd settings panel.
final stremboxdClientProvider = Provider<StremboxdClient>(
  (ref) => StremboxdClient(ref.watch(jsonTransportProvider)),
);

/// The scraped Letterboxd reviews for a detail title (films only — Letterboxd is
/// a film network). Resolves the IMDb id (a `tmdb:` id is looked up) then scrapes
/// the film's Letterboxd page. Empty for series or on any failure. Ports the
/// web detail `LetterboxdReviews`.
final letterboxdReviewsProvider =
    FutureProvider.family<List<LetterboxdReview>, ({String type, String id})>((
      ref,
      key,
    ) async {
      if (key.type != 'movie') return const [];
      final imdb = key.id.startsWith('tt')
          ? key.id
          : await ref.watch(imdbIdProvider(key.id).future);
      if (imdb == null || imdb.isEmpty) return const [];
      return fetchLetterboxdReviews(ref.watch(textTransportProvider), imdb);
    });

/// The per-profile full-mode Letterboxd session store (token in the keychain).
final letterboxdSessionStoreProvider = Provider<LetterboxdSessionStore>((ref) {
  return LetterboxdSessionStore(
    ref.watch(secureStoreProvider),
    profileId: ref.watch(profilesRepoProvider).activeProfileId(),
  );
});

/// The full-mode Letterboxd session (null when not signed in), driving the
/// panel's connected state. Hydrates the stored token, and exposes login /
/// disconnect.
class LetterboxdConnectController extends Notifier<LetterboxdSession?> {
  @override
  LetterboxdSession? build() {
    _hydrate(ref.watch(letterboxdSessionStoreProvider));
    return null;
  }

  Future<void> _hydrate(LetterboxdSessionStore store) async {
    await store.ensureHydrated();
    final s = store.read();
    if (s != null && state == null) state = s;
  }

  /// Signs in with the user-entered [password] (and [totp] when required). On
  /// success the session is stored and becomes the state.
  Future<LetterboxdLoginResult> login(
    String username,
    String password, {
    String? totp,
  }) async {
    final result = await ref
        .read(stremboxdClientProvider)
        .login(
          username,
          password,
          totp: totp,
          nowMs: DateTime.now().millisecondsSinceEpoch,
        );
    if (result is LetterboxdLoginSuccess) {
      await ref.read(letterboxdSessionStoreProvider).write(result.session);
      state = result.session;
    }
    return result;
  }

  Future<void> disconnect() async {
    await ref.read(letterboxdSessionStoreProvider).clear();
    state = null;
  }
}

final letterboxdConnectProvider =
    NotifierProvider<LetterboxdConnectController, LetterboxdSession?>(
      LetterboxdConnectController.new,
    );

/// The Letterboxd home rows built from the panel's config (and full-mode
/// session), surfaced on Home. Empty when the integration is off or no config
/// has been verified. Recomputes only when the Letterboxd settings signature or
/// the sign-in state changes.
final letterboxdHomeRowsProvider = FutureProvider<List<CatalogRow>>((
  ref,
) async {
  // A stable signature over the fields that affect the rows, so unrelated
  // settings edits don't trigger a refetch.
  ref.watch(
    settingsProvider.select((s) {
      final lb = s.getMap('letterboxd');
      String join(Object? v) =>
          (v is List) ? v.whereType<Object>().join(',') : '';
      return '${lb['enabled']}|${lb['encodedConfig']}|${lb['username']}|'
          '${join(lb['selectedCatalogs'])}|${join(lb['hiddenCatalogs'])}|'
          '${join(lb['catalogOrder'])}|${(lb['listRefs'] as List?)?.length}';
    }),
  );
  final lb = ref.read(settingsProvider).getMap('letterboxd');
  if (lb['enabled'] != true) return const [];
  final selected = ((lb['selectedCatalogs'] as List?) ?? const [])
      .whereType<String>()
      .toList();
  if (selected.isEmpty) return const [];

  final hidden = ((lb['hiddenCatalogs'] as List?) ?? const [])
      .whereType<String>()
      .toList();
  final order = ((lb['catalogOrder'] as List?) ?? const [])
      .whereType<String>()
      .toList();
  final listRefs = <LetterboxdListRef>[
    for (final r in (lb['listRefs'] as List?) ?? const [])
      ?LetterboxdListRef.fromJson(r),
  ];

  final session = ref.watch(letterboxdConnectProvider);
  var config = lb['encodedConfig']?.toString() ?? '';
  // The public config segment is fully derivable from the selections, so when it
  // hasn't been pre-generated by the settings panel — e.g. the user only flipped
  // the enable toggle, or an older build never ran Verify — recompute it here so
  // the public rows (Popular This Week, Top 250) still surface. Full mode uses
  // the session's user id instead of a segment. A persisted segment is preferred
  // so any advanced/externally-generated config round-trips unchanged.
  if (config.isEmpty && session == null) {
    config = buildStremboxdConfig(
      selectedCatalogs: selected.toSet(),
      username: lb['username']?.toString() ?? '',
      listIds: [for (final r in listRefs) r.id],
      ratings: lb['showRatingsOnPosters'] != false,
    );
  }

  return buildLetterboxdHomeRows(
    client: ref.watch(stremboxdClientProvider),
    configSegment: config,
    selectedCatalogs: selected,
    hiddenCatalogs: hidden,
    catalogOrder: order,
    session: session,
    listRefs: listRefs,
  );
});
