/// Well-known trusted release groups (encoders whose output is reliably what it
/// claims), ported from `src/lib/streams/parser/parser-trusted-groups.ts`.
library;

const Set<String> _trustedGroups = {
  'FRDS',
  'FRAMESTOR',
  'FORM',
  'EVO',
  'RARBG',
  'ETHEL',
  'FLUX',
  'QXR',
  'MEGUSTA',
  'ION10',
  'PSA',
  'AMIABLE',
  'GALAXYRG',
  'WEBDV',
  'RZEROX',
  'SIC',
  'TGX',
  'NTB',
  'NTG',
  'TEPES',
  'GECKOS',
  'SUCCESSFULCRAB',
  'SUBSPLEASE',
  'ERAI',
  'ERAIRAWS',
  'JUDAS',
  'ASW',
  'EMBER',
  'ANE',
  'CLEO',
  'BEATRICERAWS',
  'AKIHITO',
  'VODES',
  'NANDESUKA',
  'SMOL',
  'TENRAISENSEI',
  'GST',
  'ANIMEKAIZOKU',
  'REINFORCE',
  'RAWS',
  'OZR',
  'PURGATORY',
  'SHK',
  'KOTUWA',
  'KIRION',
  'COMMIE',
  'DAMEDESUYO',
  'MTBB',
  'GJM',
  'SOFCJ',
};

/// Whether [normalized] (uppercased, alphanumerics only) is a trusted group.
bool isTrustedGroup(String? normalized) =>
    normalized != null && _trustedGroups.contains(normalized);
