import test from 'node:test';import assert from 'node:assert/strict';
import {MEGA_MAN_ORDERS,METAL_GEAR_ORDER,orderedGames,playOrderFamily,initialPlayOrder} from '../src/lib/games/play-orders.ts';
test('franchise identity excludes crossover games',()=>{assert.equal(playOrderFamily({name:'Mega Man X',franchises:[{id:2104,name:'Mega Man X'}]}),'mega-man');assert.equal(playOrderFamily({name:'Metal Gear Solid',franchises:[{id:551,name:'Metal Gear Solid'}]}),'metal-gear');assert.equal(playOrderFamily({name:'Super Smash Bros.',franchises:[{id:38,name:'Mega Man'}]}),undefined);assert.equal(playOrderFamily({name:'Metal Gear',franchises:[]}),undefined)});
test('branches and alternate editions share steps',()=>{assert.equal(initialPlayOrder({igdbId:1758,name:'Mega Man Battle Network 3 Blue'}),'battle-network');assert.equal(initialPlayOrder({igdbId:0,name:'Mega Man Zero/ZX Legacy Collection'}),'zero-zx');assert.equal(MEGA_MAN_ORDERS.length,6);const bn=MEGA_MAN_ORDERS.find(b=>b.key==='battle-network')!;assert.equal(bn.entries.length,6);assert.equal(bn.entries.flatMap(e=>e.editions).length,10);assert.equal(bn.entries[2].name,'Mega Man Battle Network 3')});
test('Snake chronology reorders games without mutating release order',()=>{const before=METAL_GEAR_ORDER.entries.map(e=>e.editions[0].id);assert.deepEqual(orderedGames(METAL_GEAR_ORDER,'story').map(e=>e.editions[0].id),[379,382,5328,1985,374,377,375,376,380]);assert.deepEqual(METAL_GEAR_ORDER.entries.map(e=>e.editions[0].id),before);assert.equal(orderedGames(METAL_GEAR_ORDER,'release')[0].editions[0].id,374);assert.equal(METAL_GEAR_ORDER.entries.find(e=>e.editions[0].id===376)?.storyEndYear,2009);});

import {EXTRA_PLAY_ORDERS} from '../src/lib/games/play-order-catalog.ts';
import {initialOrderBranch,playOrderDefinition} from '../src/lib/games/play-orders.ts';
const firstIds=(family:string,branch=0,order:'story'|'release'='story')=>orderedGames(playOrderDefinition(family).branches[branch],order).map(e=>e.editions[0].id);
test('Redemption and Mafia prequels move first only in story order',()=>{assert.deepEqual(firstIds('red-dead'),[25076,434]);assert.deepEqual(firstIds('red-dead',0,'release'),[434,25076]);assert.deepEqual(firstIds('mafia'),[314276,39,40,11492]);assert.deepEqual(firstIds('mafia',0,'release'),[39,40,11492,314276]);assert.equal(playOrderFamily({igdbId:134070,name:'Mafia: Definitive Edition',franchises:[]}),'mafia');});
test('GTA universes stay separate and remasters select the right branch',()=>{assert.deepEqual(firstIds('gta'),[3262,733,732,3263,3266,730]);assert.equal(initialOrderBranch('gta',{igdbId:178125,name:'Grand Theft Auto: Vice City - The Definitive Edition'}),'gta-3d');assert.equal(initialOrderBranch('gta',{igdbId:27912,name:'Grand Theft Auto IV: Complete Edition'}),'gta-hd');assert.equal(playOrderDefinition('gta').branches[2].storyOrder,false);});
test('Life is Strange bonus stories and remasters retain original release position',()=>{assert.deepEqual(firstIds('life-is-strange'),[91247,29004,7599,62151,103283,144873,144765,305158,386431]);assert.deepEqual(firstIds('life-is-strange',0,'release'),[7599,29004,91247,103283,62151,144765,144873,305158,386431]);});
test('Telltale eligibility does not leak to unrelated licensed games',()=>{assert.equal(playOrderFamily({igdbId:117514,name:'The Walking Dead: The Telltale Definitive Series',franchises:[{id:39,name:'The Walking Dead'}],series:[{id:564,name:'The Walking Dead - A Telltale Games Series'}]}),'walking-dead');assert.equal(playOrderFamily({name:'The Walking Dead: Saints & Sinners',franchises:[{id:39,name:'The Walking Dead'}]}),undefined);assert.equal(playOrderFamily({name:'Batman: Arkham City',franchises:[{id:5,name:'Batman'}]}),undefined);assert.equal(playOrderFamily({igdbId:127560,name:'Telltale Batman Shadows Edition',franchises:[]}),'telltale-batman');assert.deepEqual(firstIds('walking-dead'),[1871,3015,3097,19000,51524]);});
test('Star Wars routes to the matching connected series',()=>{assert.equal(initialOrderBranch('star-wars',{igdbId:118,name:'Star Wars: Knights of the Old Republic II - The Sith Lords'}),'kotor');assert.deepEqual(firstIds('star-wars'),[74701,201156]);assert.deepEqual(firstIds('star-wars',2),[475,137]);});
test('catalog has bounded unique identities and complete sortable timelines',()=>{const all=new Set<number>();for(const family of EXTRA_PLAY_ORDERS)for(const branch of family.branches){assert.ok(branch.entries.length>0);assert.ok(branch.entries.flatMap(e=>e.editions).length<=50);for(const entry of branch.entries){assert.ok(entry.year>=1970);if(branch.storyOrder)assert.ok(entry.storyRank!==undefined||entry.storyYear!==undefined);for(const edition of entry.editions){assert.ok(!all.has(edition.id),String(edition.id));all.add(edition.id)}}}assert.deepEqual(firstIds('max-payne'),[18,19,960]);assert.deepEqual(firstIds('mass-effect'),[73,74,75,7349]);});

test('Witcher and other connected stories use exact original identities',()=>{assert.deepEqual(firstIds('witcher'),[80,478,1942]);assert.equal(playOrderFamily({igdbId:22439,name:'The Witcher 3: Wild Hunt - Game of the Year Edition',franchises:[]}),'witcher');assert.deepEqual(firstIds('dragon-age'),[76,78,1887,30208]);assert.deepEqual(firstIds('dishonored'),[533,11118,37030]);assert.deepEqual(firstIds('metro'),[284720,495,539,37016]);assert.deepEqual(firstIds('bioshock'),[538,20,21]);});
test('Yakuza prequel and Kiwami editions share the right story positions',()=>{assert.deepEqual(firstIds('yakuza'),[11397,2059,2060,2061,2062,2063,12527,36550,217624,217623,317317]);assert.equal(firstIds('yakuza',0,'release')[0],2059);assert.equal(initialOrderBranch('yakuza',{igdbId:55090,name:'Yakuza Kiwami 2'}),'yakuza-main');assert.equal(initialOrderBranch('yakuza',{igdbId:281562,name:'Judgment'}),'judgment');assert.equal(initialOrderBranch('yakuza',{igdbId:237573,name:'Like a Dragon: Ishin! - Digital Deluxe Edition'}),'ishin');assert.equal(initialOrderBranch('yakuza',{igdbId:7489,name:'Yakuza: Dead Souls'}),'dead-souls');});
test('Mario, Sonic and LEGO use release guides without an invented shared chronology',()=>{for(const family of ['mario','sonic','lego-star-wars'])assert.ok(playOrderDefinition(family).branches.every(b=>b.storyOrder===false));assert.equal(initialOrderBranch('mario',{igdbId:266690,name:'Paper Mario: The Thousand-Year Door'}),'paper-mario');assert.equal(initialOrderBranch('sonic',{igdbId:284716,name:'Sonic X Shadow Generations'}),'sonic-3d');assert.equal(playOrderFamily({name:'Super Mario Kart',franchises:[],series:[{id:240,name:'Super Mario'}]}),undefined);assert.equal(playOrderFamily({igdbId:119305,name:'LEGO Star Wars: The Skywalker Saga',franchises:[]}),'lego-star-wars');assert.equal(playOrderFamily({name:'Mario & Sonic at the Olympic Games',franchises:[],series:[{id:2156,name:'Sonic'}]}),undefined);});
