// Published weekly chart links from Billboard's primary directory, verified 2026-09-14.
export type BillboardChartRef = {
  id: string;
  name: string;
  group: string;
  country: string;
  kind: "track" | "album" | "artist";
};
export const BILLBOARD_CHARTS: BillboardChartRef[] = [
  {
    id: "hot-100",
    name: "Billboard Hot 100",
    group: "Top Charts",
    country: "US",
    kind: "track",
  },
  {
    id: "billboard-200",
    name: "Billboard 200",
    group: "Top Charts",
    country: "US",
    kind: "album",
  },
  {
    id: "artist-100",
    name: "Billboard Artist 100",
    group: "Top Charts",
    country: "US",
    kind: "artist",
  },
  {
    id: "emerging-artists",
    name: "Emerging Artists",
    group: "Top Charts",
    country: "US",
    kind: "artist",
  },
  {
    id: "streaming-songs",
    name: "Streaming Songs",
    group: "Top Charts",
    country: "US",
    kind: "track",
  },
  {
    id: "radio-songs",
    name: "Radio Songs",
    group: "Top Charts",
    country: "US",
    kind: "track",
  },
  {
    id: "digital-song-sales",
    name: "Digital Song Sales",
    group: "Top Charts",
    country: "US",
    kind: "track",
  },
  {
    id: "top-album-sales",
    name: "Top Album Sales",
    group: "Top Charts",
    country: "US",
    kind: "album",
  },
  {
    id: "top-streaming-albums",
    name: "Top Streaming Albums",
    group: "Top Charts",
    country: "US",
    kind: "album",
  },
  {
    id: "independent-albums",
    name: "Independent Albums",
    group: "Top Charts",
    country: "US",
    kind: "album",
  },
  {
    id: "vinyl-albums",
    name: "Vinyl Albums",
    group: "Top Charts",
    country: "US",
    kind: "album",
  },
  {
    id: "indie-store-album-sales",
    name: "Indie Store Album Sales",
    group: "Top Charts",
    country: "US",
    kind: "album",
  },
  {
    id: "billboard-global-200",
    name: "Billboard Global 200",
    group: "Global",
    country: "global",
    kind: "track",
  },
  {
    id: "billboard-global-excl-us",
    name: "Billboard Global Excl. U.S.",
    group: "Global",
    country: "global",
    kind: "track",
  },
  {
    id: "billboard-u-s-afrobeats-songs",
    name: "Billboard U.S. Afrobeats Songs",
    group: "Afrobeats",
    country: "US",
    kind: "track",
  },
  {
    id: "the-arabic-hot-100",
    name: "Billboard Arabic Hot 100",
    group: "Hits of the World",
    country: "arabic",
    kind: "track",
  },
  {
    id: "top-arabic-artist-100",
    name: "Billboard Arabic Artist 100",
    group: "Hits of the World",
    country: "arabic",
    kind: "artist",
  },
  {
    id: "billboard-argentina-hot-100",
    name: "Billboard Argentina Hot 100",
    group: "Hits of the World",
    country: "AR",
    kind: "track",
  },
  {
    id: "billboard-brasil-hot-100",
    name: "Billboard Brasil Hot 100",
    group: "Hits of the World",
    country: "BR",
    kind: "track",
  },
  {
    id: "canadian-hot-100",
    name: "Billboard Canadian Hot 100",
    group: "Hits of the World",
    country: "CA",
    kind: "track",
  },
  {
    id: "canadian-albums",
    name: "Billboard Canadian Albums",
    group: "Hits of the World",
    country: "CA",
    kind: "album",
  },
  {
    id: "billboard-colombia-hot-100",
    name: "Billboard Colombia Hot 100",
    group: "Hits of the World",
    country: "CO",
    kind: "track",
  },
  {
    id: "billboard-italy-hot-100",
    name: "Billboard Italy Hot 100",
    group: "Hits of the World",
    country: "IT",
    kind: "track",
  },
  {
    id: "billboard-italy-albums-top-100",
    name: "Billboard Italy Albums Top 100",
    group: "Hits of the World",
    country: "IT",
    kind: "album",
  },
  {
    id: "japan-hot-100",
    name: "Billboard Japan Hot 100",
    group: "Hits of the World",
    country: "JP",
    kind: "track",
  },
  {
    id: "billboard-korea-global-k-songs",
    name: "Billboard Korea Global K-Songs",
    group: "Hits of the World",
    country: "KR",
    kind: "track",
  },
  {
    id: "billboard-philippines-hot-100",
    name: "Billboard Philippines Hot 100",
    group: "Hits of the World",
    country: "PH",
    kind: "track",
  },
  {
    id: "billboard-philippines-top-philippine-songs",
    name: "Billboard Philippines Top Philippine Songs",
    group: "Hits of the World",
    country: "PH",
    kind: "track",
  },
  {
    id: "billboard-vietnam-hot-100-songs",
    name: "Billboard Vietnam Hot 100",
    group: "Hits of the World",
    country: "VN",
    kind: "track",
  },
  {
    id: "billboard-vietnam-top-vietnamese-songs",
    name: "Billboard Vietnam Top Vietnamese Songs",
    group: "Hits of the World",
    country: "VN",
    kind: "track",
  },
  {
    id: "official-uk-songs",
    name: "The Official U.K. Singles Chart",
    group: "Hits of the World",
    country: "GB",
    kind: "track",
  },
  {
    id: "official-uk-albums",
    name: "The Official U.K. Albums Chart",
    group: "Hits of the World",
    country: "GB",
    kind: "album",
  },
  {
    id: "australia-songs-hotw",
    name: "Australia Songs",
    group: "Hits of the World",
    country: "AU",
    kind: "track",
  },
  {
    id: "australian-albums",
    name: "Australia Albums",
    group: "Hits of the World",
    country: "AU",
    kind: "album",
  },
  {
    id: "austria-songs-hotw",
    name: "Austria Songs",
    group: "Hits of the World",
    country: "AT",
    kind: "track",
  },
  {
    id: "belgium-songs-hotw",
    name: "Belgium Songs",
    group: "Hits of the World",
    country: "BE",
    kind: "track",
  },
  {
    id: "bolivia-songs-hotw",
    name: "Bolivia Songs",
    group: "Hits of the World",
    country: "BO",
    kind: "track",
  },
  {
    id: "chile-songs-hotw",
    name: "Chile Songs",
    group: "Hits of the World",
    country: "CL",
    kind: "track",
  },
  {
    id: "china-tme-uni-songs",
    name: "China TME UNI Chart",
    group: "Hits of the World",
    country: "CN",
    kind: "track",
  },
  {
    id: "croatia-songs-hotw",
    name: "Croatia Songs",
    group: "Hits of the World",
    country: "HR",
    kind: "track",
  },
  {
    id: "czech-republic-songs-hotw",
    name: "Czech Republic Songs",
    group: "Hits of the World",
    country: "CZ",
    kind: "track",
  },
  {
    id: "denmark-songs-hotw",
    name: "Denmark Songs",
    group: "Hits of the World",
    country: "DK",
    kind: "track",
  },
  {
    id: "ecuador-songs-hotw",
    name: "Ecuador Songs",
    group: "Hits of the World",
    country: "EC",
    kind: "track",
  },
  {
    id: "finland-songs-hotw",
    name: "Finland Songs",
    group: "Hits of the World",
    country: "FI",
    kind: "track",
  },
  {
    id: "france-songs-hotw",
    name: "France Songs",
    group: "Hits of the World",
    country: "FR",
    kind: "track",
  },
  {
    id: "germany-songs-hotw",
    name: "Germany Songs",
    group: "Hits of the World",
    country: "DE",
    kind: "track",
  },
  {
    id: "greece-songs-hotw",
    name: "Greece Songs",
    group: "Hits of the World",
    country: "GR",
    kind: "track",
  },
  {
    id: "greece-albums",
    name: "Greece Albums",
    group: "Hits of the World",
    country: "GR",
    kind: "album",
  },
  {
    id: "hong-kong-songs-hotw",
    name: "Hong Kong Songs",
    group: "Hits of the World",
    country: "HK",
    kind: "track",
  },
  {
    id: "hungary-songs-hotw",
    name: "Hungary Songs",
    group: "Hits of the World",
    country: "HU",
    kind: "track",
  },
  {
    id: "iceland-songs-hotw",
    name: "Iceland Songs",
    group: "Hits of the World",
    country: "IS",
    kind: "track",
  },
  {
    id: "india-songs-hotw",
    name: "India Songs",
    group: "Hits of the World",
    country: "IN",
    kind: "track",
  },
  {
    id: "indonesia-songs-hotw",
    name: "Indonesia Songs",
    group: "Hits of the World",
    country: "ID",
    kind: "track",
  },
  {
    id: "ireland-songs-hotw",
    name: "Ireland Songs",
    group: "Hits of the World",
    country: "IE",
    kind: "track",
  },
  {
    id: "luxembourg-songs-hotw",
    name: "Luxembourg Songs",
    group: "Hits of the World",
    country: "LU",
    kind: "track",
  },
  {
    id: "malaysia-songs-hotw",
    name: "Malaysia Songs",
    group: "Hits of the World",
    country: "MY",
    kind: "track",
  },
  {
    id: "mexico-songs-hotw",
    name: "Mexico Songs",
    group: "Hits of the World",
    country: "MX",
    kind: "track",
  },
  {
    id: "netherlands-songs-hotw",
    name: "Netherlands Songs",
    group: "Hits of the World",
    country: "NL",
    kind: "track",
  },
  {
    id: "new-zealand-songs-hotw",
    name: "New Zealand Songs",
    group: "Hits of the World",
    country: "NZ",
    kind: "track",
  },
  {
    id: "norway-songs-hotw",
    name: "Norway Songs",
    group: "Hits of the World",
    country: "NO",
    kind: "track",
  },
  {
    id: "peru-songs-hotw",
    name: "Peru Songs",
    group: "Hits of the World",
    country: "PE",
    kind: "track",
  },
  {
    id: "poland-songs-hotw",
    name: "Poland Songs",
    group: "Hits of the World",
    country: "PL",
    kind: "track",
  },
  {
    id: "portugal-songs-hotw",
    name: "Portugal Songs",
    group: "Hits of the World",
    country: "PT",
    kind: "track",
  },
  {
    id: "romania-songs-hotw",
    name: "Romania Songs",
    group: "Hits of the World",
    country: "RO",
    kind: "track",
  },
  {
    id: "singapore-songs-hotw",
    name: "Singapore Songs",
    group: "Hits of the World",
    country: "SG",
    kind: "track",
  },
  {
    id: "slovakia-songs-hotw",
    name: "Slovakia Songs",
    group: "Hits of the World",
    country: "SK",
    kind: "track",
  },
  {
    id: "south-africa-songs-hotw",
    name: "South Africa Songs",
    group: "Hits of the World",
    country: "ZA",
    kind: "track",
  },
  {
    id: "spain-songs-hotw",
    name: "Spain Songs",
    group: "Hits of the World",
    country: "ES",
    kind: "track",
  },
  {
    id: "sweden-songs-hotw",
    name: "Sweden Songs",
    group: "Hits of the World",
    country: "SE",
    kind: "track",
  },
  {
    id: "switzerland-songs-hotw",
    name: "Switzerland Songs",
    group: "Hits of the World",
    country: "CH",
    kind: "track",
  },
  {
    id: "taiwan-songs-hotw",
    name: "Taiwan Songs",
    group: "Hits of the World",
    country: "TW",
    kind: "track",
  },
  {
    id: "thailand-songs-hotw",
    name: "Thailand Songs",
    group: "Hits of the World",
    country: "TH",
    kind: "track",
  },
  {
    id: "turkey-songs-hotw",
    name: "Turkey Songs",
    group: "Hits of the World",
    country: "TR",
    kind: "track",
  },
  {
    id: "u-k-songs-hotw",
    name: "U.K. Songs",
    group: "Hits of the World",
    country: "GB",
    kind: "track",
  },
  {
    id: "pop-songs",
    name: "Pop Airplay",
    group: "Pop",
    country: "US",
    kind: "track",
  },
  {
    id: "adult-contemporary",
    name: "Adult Contemporary",
    group: "Pop",
    country: "US",
    kind: "track",
  },
  {
    id: "adult-pop-songs",
    name: "Adult Pop Airplay",
    group: "Pop",
    country: "US",
    kind: "track",
  },
  {
    id: "country-songs",
    name: "Hot Country Songs",
    group: "Country",
    country: "US",
    kind: "track",
  },
  {
    id: "country-albums",
    name: "Top Country Albums",
    group: "Country",
    country: "US",
    kind: "album",
  },
  {
    id: "country-streaming-songs",
    name: "Country Streaming Songs",
    group: "Country",
    country: "US",
    kind: "track",
  },
  {
    id: "country-airplay",
    name: "Country Airplay",
    group: "Country",
    country: "US",
    kind: "track",
  },
  {
    id: "bluegrass-albums",
    name: "Bluegrass Albums",
    group: "Country",
    country: "US",
    kind: "album",
  },
  {
    id: "americana-folk-albums",
    name: "Americana/Folk Albums",
    group: "Country",
    country: "US",
    kind: "album",
  },
  {
    id: "rock-songs",
    name: "Hot Rock & Alternative Songs",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "top-rock-alternative-albums",
    name: "Top Rock & Alternative Albums",
    group: "Rock & Alternative",
    country: "US",
    kind: "album",
  },
  {
    id: "rock-airplay",
    name: "Rock & Alternative Airplay",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-rock-songs",
    name: "Hot Rock Songs",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "rock-albums",
    name: "Top Rock Albums",
    group: "Rock & Alternative",
    country: "US",
    kind: "album",
  },
  {
    id: "rock-streaming-songs",
    name: "Rock Streaming Songs",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-alternative-songs",
    name: "Hot Alternative Songs",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "alternative-albums",
    name: "Top Alternative Albums",
    group: "Rock & Alternative",
    country: "US",
    kind: "album",
  },
  {
    id: "alternative-streaming-songs",
    name: "Alternative Streaming Songs",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "alternative-airplay",
    name: "Alternative Airplay",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-hard-rock-songs",
    name: "Hot Hard Rock Songs",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "hard-rock-albums",
    name: "Top Hard Rock Albums",
    group: "Rock & Alternative",
    country: "US",
    kind: "album",
  },
  {
    id: "hard-rock-streaming-songs",
    name: "Hard Rock Streaming Songs",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "triple-a",
    name: "Adult Alternative Airplay",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-mainstream-rock-tracks",
    name: "Mainstream Rock Airplay",
    group: "Rock & Alternative",
    country: "US",
    kind: "track",
  },
  {
    id: "r-b-hip-hop-songs",
    name: "Hot R&B/Hip-Hop Songs",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "r-b-hip-hop-albums",
    name: "Top R&B/Hip-Hop Albums",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "album",
  },
  {
    id: "r-and-b-hip-hop-streaming-songs",
    name: "R&B/Hip-Hop Streaming Songs",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-r-and-b-hip-hop-airplay",
    name: "R&B/Hip-Hop Airplay",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "r-and-b-songs",
    name: "Hot R&B Songs",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "r-and-b-albums",
    name: "Top R&B Albums",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "album",
  },
  {
    id: "r-and-b-streaming-songs",
    name: "R&B Streaming Songs",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "rap-song",
    name: "Hot Rap Songs",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "rap-albums",
    name: "Top Rap Albums",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "album",
  },
  {
    id: "rap-streaming-songs",
    name: "Rap Streaming Songs",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-rap-tracks",
    name: "Rap Airplay",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "mainstream-r-and-b-hip-hop",
    name: "Mainstream R&B/Hip-Hop Airplay",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-adult-r-and-b-airplay",
    name: "Adult R&B Airplay",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "rhythmic-40",
    name: "Rhythmic Airplay",
    group: "R&B/Hip-Hop",
    country: "US",
    kind: "track",
  },
  {
    id: "latin-songs",
    name: "Hot Latin Songs",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "latin-albums",
    name: "Top Latin Albums",
    group: "Latin",
    country: "US",
    kind: "album",
  },
  {
    id: "latin-airplay",
    name: "Latin Airplay",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "latin-streaming-songs",
    name: "Latin Streaming Songs",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-regional-mexican-songs",
    name: "Hot Regional Mexican Songs",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "regional-mexican-albums",
    name: "Top Regional Mexican Albums",
    group: "Latin",
    country: "US",
    kind: "album",
  },
  {
    id: "latin-regional-mexican-airplay",
    name: "Regional Mexican Airplay",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-latin-pop-songs",
    name: "Hot Latin Pop Songs",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "latin-pop-albums",
    name: "Top Latin Pop Albums",
    group: "Latin",
    country: "US",
    kind: "album",
  },
  {
    id: "latin-pop-airplay",
    name: "Latin Pop Airplay",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-tropical-songs",
    name: "Hot Tropical Songs",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "tropical-albums",
    name: "Top Tropical Albums",
    group: "Latin",
    country: "US",
    kind: "album",
  },
  {
    id: "latin-tropical-airplay",
    name: "Tropical Airplay",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-latin-rhythm-songs",
    name: "Hot Latin Rhythm Songs",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "latin-rhythm-albums",
    name: "Top Latin Rhythm Albums",
    group: "Latin",
    country: "US",
    kind: "album",
  },
  {
    id: "latin-rhythm-airplay",
    name: "Latin Rhythm Airplay",
    group: "Latin",
    country: "US",
    kind: "track",
  },
  {
    id: "dance-electronic-songs",
    name: "Hot Dance/Electronic Songs",
    group: "Dance",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-dance-pop-songs",
    name: "Hot Dance/Pop Songs",
    group: "Dance",
    country: "US",
    kind: "track",
  },
  {
    id: "dance-electronic-albums",
    name: "Top Dance Albums",
    group: "Dance",
    country: "US",
    kind: "album",
  },
  {
    id: "hot-dance-airplay",
    name: "Dance Airplay",
    group: "Dance",
    country: "US",
    kind: "track",
  },
  {
    id: "warm-global-dance-radio",
    name: "WARM Global Dance Radio",
    group: "Dance",
    country: "global",
    kind: "track",
  },
  {
    id: "dance-electronic-streaming-songs",
    name: "Dance Streaming Songs",
    group: "Dance",
    country: "US",
    kind: "track",
  },
  {
    id: "christian-songs",
    name: "Hot Christian Songs",
    group: "Christian",
    country: "US",
    kind: "track",
  },
  {
    id: "christian-albums",
    name: "Top Christian Albums",
    group: "Christian",
    country: "US",
    kind: "album",
  },
  {
    id: "christian-streaming-songs",
    name: "Christian Streaming Songs",
    group: "Christian",
    country: "US",
    kind: "track",
  },
  {
    id: "christian-airplay",
    name: "Christian Airplay",
    group: "Christian",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-christian-adult-contemporary",
    name: "Christian AC Airplay",
    group: "Christian",
    country: "US",
    kind: "track",
  },
  {
    id: "gospel-songs",
    name: "Hot Gospel Songs",
    group: "Gospel",
    country: "US",
    kind: "track",
  },
  {
    id: "gospel-albums",
    name: "Top Gospel Albums",
    group: "Gospel",
    country: "US",
    kind: "album",
  },
  {
    id: "gospel-streaming-songs",
    name: "Gospel Streaming Songs",
    group: "Gospel",
    country: "US",
    kind: "track",
  },
  {
    id: "gospel-airplay",
    name: "Gospel Airplay",
    group: "Gospel",
    country: "US",
    kind: "track",
  },
  {
    id: "hot-100-songwriters",
    name: "Hot 100 Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "hot-100-producers",
    name: "Hot 100 Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "country-songwriters",
    name: "Country Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "country-producers",
    name: "Country Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "rock-alternative-songwriters",
    name: "Rock & Alternative Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "rock-alternative-producers",
    name: "Rock & Alternative Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "rock-songwriters",
    name: "Rock Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "rock-producers",
    name: "Rock Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "alternative-songwriters",
    name: "Alternative Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "alternative-producers",
    name: "Alternative Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "hard-rock-songwriters",
    name: "Hard Rock Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "hard-rock-producers",
    name: "Hard Rock Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "rb-hip-hop-songwriters",
    name: "R&B/Hip-Hop Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "rb-hip-hop-producers",
    name: "R&B/Hip-Hop Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "rb-songwriters",
    name: "R&B Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "rb-producers",
    name: "R&B Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "rap-songwriters",
    name: "Rap Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "rap-producers",
    name: "Rap Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "latin-songwriters",
    name: "Latin Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "latin-producers",
    name: "Latin Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "dance-electronic-songwriters",
    name: "Dance/Electronic Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "dance-electronic-producers",
    name: "Dance/Electronic Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "dance-pop-songwriters",
    name: "Dance/Pop Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "dance-pop-producers",
    name: "Dance/Pop Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "christian-songwriters",
    name: "Christian Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "christian-producers",
    name: "Christian Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "gospel-songwriters",
    name: "Gospel Songwriters",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "gospel-producers",
    name: "Gospel Producers",
    group: "Songwriters & Producers",
    country: "US",
    kind: "artist",
  },
  {
    id: "classical-albums",
    name: "Classical Albums",
    group: "Classical",
    country: "US",
    kind: "album",
  },
  {
    id: "classical-crossover-albums",
    name: "Classical Crossover Albums",
    group: "Classical",
    country: "US",
    kind: "album",
  },
  {
    id: "traditional-classic-albums",
    name: "Traditional Classical Albums",
    group: "Classical",
    country: "US",
    kind: "album",
  },
  {
    id: "jazz-albums",
    name: "Jazz Albums",
    group: "Jazz",
    country: "US",
    kind: "album",
  },
  {
    id: "contemporary-jazz",
    name: "Contemporary Jazz Albums",
    group: "Jazz",
    country: "US",
    kind: "album",
  },
  {
    id: "traditional-jazz-albums",
    name: "Traditional Jazz Albums",
    group: "Jazz",
    country: "US",
    kind: "album",
  },
  {
    id: "jazz-songs",
    name: "Smooth Jazz Airplay",
    group: "Jazz",
    country: "US",
    kind: "track",
  },
  {
    id: "world-albums",
    name: "World Albums",
    group: "World",
    country: "US",
    kind: "album",
  },
  {
    id: "hot-holiday-songs",
    name: "Holiday 100",
    group: "Holiday",
    country: "US",
    kind: "track",
  },
  {
    id: "holiday-albums",
    name: "Top Holiday Albums",
    group: "Holiday",
    country: "US",
    kind: "album",
  },
  {
    id: "holiday-streaming-songs",
    name: "Holiday Streaming Songs",
    group: "Holiday",
    country: "US",
    kind: "track",
  },
  {
    id: "holiday-songs",
    name: "Holiday Airplay",
    group: "Holiday",
    country: "US",
    kind: "track",
  },
  {
    id: "holiday-100-songwriters",
    name: "Holiday 100 Songwriters",
    group: "Holiday",
    country: "US",
    kind: "artist",
  },
  {
    id: "holiday-100-producers",
    name: "Holiday 100 Producers",
    group: "Holiday",
    country: "US",
    kind: "artist",
  },
  {
    id: "summer-songs",
    name: "Songs of the Summer",
    group: "Summer",
    country: "US",
    kind: "track",
  },
  {
    id: "cast-albums",
    name: "Cast Albums",
    group: "Stage & Screen",
    country: "US",
    kind: "album",
  },
  {
    id: "soundtracks",
    name: "Soundtracks",
    group: "Stage & Screen",
    country: "US",
    kind: "album",
  },
  {
    id: "blues-albums",
    name: "Blues Albums",
    group: "Additional Genres",
    country: "US",
    kind: "album",
  },
  {
    id: "comedy-albums",
    name: "Comedy Albums",
    group: "Additional Genres",
    country: "US",
    kind: "album",
  },
  {
    id: "kids-albums",
    name: "Kid Albums",
    group: "Additional Genres",
    country: "US",
    kind: "album",
  },
  {
    id: "new-age-albums",
    name: "New Age Albums",
    group: "Additional Genres",
    country: "US",
    kind: "album",
  },
  {
    id: "reggae-albums",
    name: "Reggae Albums",
    group: "Additional Genres",
    country: "US",
    kind: "album",
  },
  {
    id: "bubbling-under-hot-100-singles",
    name: "Bubbling Under Hot 100",
    group: "Additional Charts",
    country: "US",
    kind: "track",
  },
  {
    id: "lyricfind-us",
    name: "LyricFind U.S.",
    group: "Additional Charts",
    country: "US",
    kind: "track",
  },
  {
    id: "lyricfind-global",
    name: "LyricFind Global",
    group: "Additional Charts",
    country: "global",
    kind: "track",
  },
];
