/// A curated movie-franchise collection: its TMDB collection id (0 when unknown,
/// healed at render time by a name search) and its display categories. Ported
/// 1:1 from `src/lib/collections-catalog.ts`.
class CatalogCollection {
  const CatalogCollection({
    required this.id,
    required this.name,
    required this.cats,
  });

  final int id;
  final String name;
  final List<String> cats;
}

/// The collection filter categories, in order.
const List<String> kCollectionCategories = [
  'Sagas',
  'Superheroes',
  'Action',
  'Adventure',
  'Sci-Fi',
  'Fantasy',
  'Animation',
  'Horror',
  'Comedy',
  'Crime',
];

/// The curated collections catalog shown on Home and the Collections grid.
const List<CatalogCollection> kCollectionsCatalog = [
  CatalogCollection(id: 10, name: "Star Wars", cats: ["Sagas", "Sci-Fi"]),
  CatalogCollection(id: 1241, name: "Harry Potter", cats: ["Sagas", "Fantasy"]),
  CatalogCollection(
    id: 119,
    name: "The Lord of the Rings",
    cats: ["Sagas", "Fantasy"],
  ),
  CatalogCollection(id: 121938, name: "The Hobbit", cats: ["Sagas", "Fantasy"]),
  CatalogCollection(
    id: 263,
    name: "The Dark Knight Trilogy",
    cats: ["Superheroes", "Crime"],
  ),
  CatalogCollection(
    id: 328,
    name: "Jurassic Park",
    cats: ["Adventure", "Sci-Fi"],
  ),
  CatalogCollection(id: 87096, name: "Avatar", cats: ["Sagas", "Sci-Fi"]),
  CatalogCollection(
    id: 9485,
    name: "The Fast and the Furious",
    cats: ["Action"],
  ),
  CatalogCollection(id: 87359, name: "Mission: Impossible", cats: ["Action"]),
  CatalogCollection(id: 645, name: "James Bond 007", cats: ["Action"]),
  CatalogCollection(
    id: 295,
    name: "Pirates of the Caribbean",
    cats: ["Adventure", "Fantasy"],
  ),
  CatalogCollection(id: 2344, name: "The Matrix", cats: ["Sci-Fi", "Action"]),
  CatalogCollection(id: 404609, name: "John Wick", cats: ["Action"]),
  CatalogCollection(id: 84, name: "Indiana Jones", cats: ["Adventure"]),
  CatalogCollection(id: 8091, name: "Alien", cats: ["Sci-Fi", "Horror"]),
  CatalogCollection(id: 399, name: "Predator", cats: ["Sci-Fi", "Action"]),
  CatalogCollection(
    id: 528,
    name: "The Terminator",
    cats: ["Sci-Fi", "Action"],
  ),
  CatalogCollection(
    id: 264,
    name: "Back to the Future",
    cats: ["Sci-Fi", "Adventure", "Comedy"],
  ),
  CatalogCollection(
    id: 131635,
    name: "The Hunger Games",
    cats: ["Sagas", "Sci-Fi"],
  ),
  CatalogCollection(id: 1575, name: "Rocky", cats: ["Action"]),
  CatalogCollection(id: 8945, name: "Mad Max", cats: ["Action", "Sci-Fi"]),
  CatalogCollection(id: 1570, name: "Die Hard", cats: ["Action"]),
  CatalogCollection(id: 86311, name: "The Avengers", cats: ["Superheroes"]),
  CatalogCollection(
    id: 284433,
    name: "Guardians of the Galaxy",
    cats: ["Superheroes", "Comedy"],
  ),
  CatalogCollection(
    id: 448150,
    name: "Deadpool",
    cats: ["Superheroes", "Comedy"],
  ),
  CatalogCollection(id: 556, name: "Spider-Man", cats: ["Superheroes"]),
  CatalogCollection(id: 748, name: "X-Men", cats: ["Superheroes"]),
  CatalogCollection(id: 8650, name: "Transformers", cats: ["Action", "Sci-Fi"]),
  CatalogCollection(id: 726871, name: "Dune", cats: ["Sagas", "Sci-Fi"]),
  CatalogCollection(id: 173710, name: "Planet of the Apes", cats: ["Sci-Fi"]),
  CatalogCollection(id: 31562, name: "The Bourne Series", cats: ["Action"]),
  CatalogCollection(id: 134004, name: "Taken", cats: ["Action"]),
  CatalogCollection(id: 126125, name: "The Expendables", cats: ["Action"]),
  CatalogCollection(id: 2883, name: "Kill Bill", cats: ["Action", "Crime"]),
  CatalogCollection(
    id: 2980,
    name: "Ghostbusters",
    cats: ["Comedy", "Fantasy"],
  ),
  CatalogCollection(
    id: 86055,
    name: "Men in Black",
    cats: ["Sci-Fi", "Comedy"],
  ),
  CatalogCollection(id: 304, name: "Ocean's", cats: ["Crime", "Comedy"]),
  CatalogCollection(
    id: 138101,
    name: "Sherlock Holmes",
    cats: ["Crime", "Adventure"],
  ),
  CatalogCollection(id: 230, name: "The Godfather", cats: ["Crime"]),
  CatalogCollection(id: 8675, name: "The Mummy", cats: ["Adventure", "Horror"]),
  CatalogCollection(
    id: 313086,
    name: "The Conjuring Universe",
    cats: ["Horror"],
  ),
  CatalogCollection(id: 91361, name: "Halloween", cats: ["Horror"]),
  CatalogCollection(id: 656, name: "Saw", cats: ["Horror"]),
  CatalogCollection(id: 2602, name: "Scream", cats: ["Horror"]),
  CatalogCollection(
    id: 8581,
    name: "A Nightmare on Elm Street",
    cats: ["Horror"],
  ),
  CatalogCollection(
    id: 17255,
    name: "Resident Evil",
    cats: ["Horror", "Action"],
  ),
  CatalogCollection(
    id: 720879,
    name: "Sonic the Hedgehog",
    cats: ["Animation", "Adventure"],
  ),
  CatalogCollection(id: 10194, name: "Toy Story", cats: ["Animation"]),
  CatalogCollection(
    id: 468222,
    name: "The Incredibles",
    cats: ["Animation", "Superheroes"],
  ),
  CatalogCollection(id: 137697, name: "Finding Nemo", cats: ["Animation"]),
  CatalogCollection(id: 137696, name: "Monsters, Inc.", cats: ["Animation"]),
  CatalogCollection(id: 87118, name: "Cars", cats: ["Animation"]),
  CatalogCollection(id: 386382, name: "Frozen", cats: ["Animation", "Fantasy"]),
  CatalogCollection(id: 2150, name: "Shrek", cats: ["Animation", "Comedy"]),
  CatalogCollection(
    id: 14890,
    name: "Madagascar",
    cats: ["Animation", "Comedy"],
  ),
  CatalogCollection(
    id: 89137,
    name: "How to Train Your Dragon",
    cats: ["Animation", "Fantasy"],
  ),
  CatalogCollection(
    id: 77816,
    name: "Kung Fu Panda",
    cats: ["Animation", "Comedy"],
  ),
  CatalogCollection(
    id: 86066,
    name: "Despicable Me",
    cats: ["Animation", "Comedy"],
  ),
  CatalogCollection(id: 8354, name: "Ice Age", cats: ["Animation", "Comedy"]),
  CatalogCollection(
    id: 420,
    name: "The Chronicles of Narnia",
    cats: ["Fantasy", "Adventure"],
  ),
  CatalogCollection(id: 0, name: "Star Trek", cats: ["Sci-Fi", "Sagas"]),
  CatalogCollection(id: 0, name: "Rambo", cats: ["Action"]),
  CatalogCollection(id: 0, name: "Lethal Weapon", cats: ["Action", "Crime"]),
  CatalogCollection(id: 0, name: "Bad Boys", cats: ["Action", "Comedy"]),
  CatalogCollection(id: 0, name: "Rush Hour", cats: ["Action", "Comedy"]),
  CatalogCollection(id: 0, name: "The Equalizer", cats: ["Action"]),
  CatalogCollection(id: 0, name: "Top Gun", cats: ["Action"]),
  CatalogCollection(id: 0, name: "Creed", cats: ["Action"]),
  CatalogCollection(
    id: 0,
    name: "The Karate Kid",
    cats: ["Action", "Adventure"],
  ),
  CatalogCollection(id: 0, name: "Blade", cats: ["Superheroes", "Horror"]),
  CatalogCollection(id: 0, name: "Hellboy", cats: ["Superheroes", "Fantasy"]),
  CatalogCollection(id: 0, name: "Wonder Woman", cats: ["Superheroes"]),
  CatalogCollection(id: 0, name: "Aquaman", cats: ["Superheroes"]),
  CatalogCollection(id: 0, name: "Venom", cats: ["Superheroes"]),
  CatalogCollection(id: 0, name: "Thor", cats: ["Superheroes"]),
  CatalogCollection(id: 0, name: "Captain America", cats: ["Superheroes"]),
  CatalogCollection(id: 0, name: "Iron Man", cats: ["Superheroes"]),
  CatalogCollection(id: 0, name: "Ant-Man", cats: ["Superheroes", "Comedy"]),
  CatalogCollection(
    id: 0,
    name: "Doctor Strange",
    cats: ["Superheroes", "Fantasy"],
  ),
  CatalogCollection(id: 0, name: "Black Panther", cats: ["Superheroes"]),
  CatalogCollection(
    id: 0,
    name: "Fantastic Beasts",
    cats: ["Fantasy", "Sagas"],
  ),
  CatalogCollection(
    id: 0,
    name: "The Maze Runner",
    cats: ["Sci-Fi", "Adventure"],
  ),
  CatalogCollection(id: 0, name: "Divergent", cats: ["Sci-Fi", "Adventure"]),
  CatalogCollection(
    id: 0,
    name: "Percy Jackson",
    cats: ["Fantasy", "Adventure"],
  ),
  CatalogCollection(
    id: 0,
    name: "The Twilight Saga",
    cats: ["Fantasy", "Sagas"],
  ),
  CatalogCollection(id: 0, name: "Pacific Rim", cats: ["Sci-Fi", "Action"]),
  CatalogCollection(id: 0, name: "Cloverfield", cats: ["Sci-Fi", "Horror"]),
  CatalogCollection(id: 0, name: "A Quiet Place", cats: ["Horror", "Sci-Fi"]),
  CatalogCollection(id: 0, name: "The Purge", cats: ["Horror"]),
  CatalogCollection(id: 0, name: "Insidious", cats: ["Horror"]),
  CatalogCollection(id: 0, name: "Annabelle", cats: ["Horror"]),
  CatalogCollection(id: 0, name: "Final Destination", cats: ["Horror"]),
  CatalogCollection(id: 0, name: "Paranormal Activity", cats: ["Horror"]),
  CatalogCollection(id: 0, name: "Child's Play", cats: ["Horror"]),
  CatalogCollection(
    id: 0,
    name: "The Texas Chainsaw Massacre",
    cats: ["Horror"],
  ),
  CatalogCollection(id: 0, name: "Evil Dead", cats: ["Horror"]),
  CatalogCollection(id: 0, name: "Underworld", cats: ["Horror", "Action"]),
  CatalogCollection(id: 0, name: "Godzilla", cats: ["Sci-Fi", "Action"]),
  CatalogCollection(id: 0, name: "Knives Out", cats: ["Crime", "Comedy"]),
  CatalogCollection(id: 0, name: "Now You See Me", cats: ["Crime"]),
  CatalogCollection(id: 0, name: "National Treasure", cats: ["Adventure"]),
  CatalogCollection(
    id: 0,
    name: "Night at the Museum",
    cats: ["Comedy", "Fantasy"],
  ),
  CatalogCollection(id: 0, name: "21 Jump Street", cats: ["Comedy", "Action"]),
  CatalogCollection(id: 0, name: "Pitch Perfect", cats: ["Comedy"]),
  CatalogCollection(id: 0, name: "Mamma Mia!", cats: ["Comedy"]),
  CatalogCollection(id: 0, name: "Bridget Jones", cats: ["Comedy"]),
  CatalogCollection(
    id: 0,
    name: "Hotel Transylvania",
    cats: ["Animation", "Comedy"],
  ),
  CatalogCollection(
    id: 0,
    name: "The Secret Life of Pets",
    cats: ["Animation", "Comedy"],
  ),
  CatalogCollection(id: 0, name: "Sing", cats: ["Animation"]),
  CatalogCollection(id: 0, name: "Trolls", cats: ["Animation"]),
  CatalogCollection(id: 0, name: "Minions", cats: ["Animation", "Comedy"]),
  CatalogCollection(
    id: 0,
    name: "The Lego Movie",
    cats: ["Animation", "Comedy"],
  ),
  CatalogCollection(
    id: 0,
    name: "Spider-Man: Spider-Verse",
    cats: ["Animation", "Superheroes"],
  ),
  CatalogCollection(id: 0, name: "Kingsman", cats: ["Action", "Comedy"]),
  CatalogCollection(id: 0, name: "Sicario", cats: ["Crime", "Action"]),
  CatalogCollection(id: 0, name: "Zoolander", cats: ["Comedy"]),
  CatalogCollection(id: 0, name: "Austin Powers", cats: ["Comedy"]),
  CatalogCollection(id: 0, name: "Scary Movie", cats: ["Comedy", "Horror"]),
  CatalogCollection(id: 0, name: "The Hangover", cats: ["Comedy"]),
  CatalogCollection(id: 0, name: "Jackass", cats: ["Comedy"]),
  CatalogCollection(id: 0, name: "Magic Mike", cats: ["Comedy"]),
  CatalogCollection(id: 0, name: "Fifty Shades", cats: ["Sagas"]),
  CatalogCollection(id: 0, name: "After", cats: ["Sagas"]),
  CatalogCollection(id: 0, name: "To All the Boys", cats: ["Comedy"]),
  CatalogCollection(id: 0, name: "The Princess Diaries", cats: ["Comedy"]),
];
