import type { LeagueDef, LeagueGroupDef } from "./espn-types";

export type AdditionalSportsLeague = LeagueDef & {
  officialWebsite: string;
  /** Schedule feeds can include final scores, but do not provide a reliable live scoreboard. */
  coverage: "scoreboard" | "schedule";
};

// IDs and badge URLs verified against the provider catalog; fetch only selected leagues.
const calendars = [
  [
    "VNL_M",
    "Volleyball Nations League · Men",
    "5083",
    "volleyball",
    "https://r2.thesportsdb.com/images/media/league/badge/vy2eo01625239301.png",
    "https://en.volleyballworld.com/volleyball/competitions/volleyball-nations-league/",
  ],
  [
    "VNL_W",
    "Volleyball Nations League · Women",
    "5084",
    "volleyball",
    "https://r2.thesportsdb.com/images/media/league/badge/t36s6v1732874074.png",
    "https://en.volleyballworld.com/volleyball/competitions/volleyball-nations-league/",
  ],
  [
    "ITALY_VB",
    "Italian SuperLega",
    "4544",
    "volleyball",
    "https://r2.thesportsdb.com/images/media/league/badge/vydgs81785498499.png",
    "https://www.legavolley.it/",
  ],
  [
    "ITALY_VBW",
    "Italian Serie A1 · Women",
    "4584",
    "volleyball",
    "https://r2.thesportsdb.com/images/media/league/badge/y0k0rw1555615564.png",
    "https://www.legavolleyfemminile.it/",
  ],
  [
    "PLUSLIGA",
    "Polish PlusLiga",
    "5619",
    "volleyball",
    "https://r2.thesportsdb.com/images/media/league/badge/n0zkno1746542488.png",
    "https://www.plusliga.pl/",
  ],
  [
    "CEV_CL",
    "CEV Champions League",
    "5616",
    "volleyball",
    "https://r2.thesportsdb.com/images/media/league/badge/4etf981746458741.png",
    "https://www.cev.eu/",
  ],
  [
    "EHF_CL",
    "EHF Champions League · Men",
    "4980",
    "handball",
    "https://r2.thesportsdb.com/images/media/league/badge/px6tl61704207123.png",
    "https://www.eurohandball.com/",
  ],
  [
    "EHF_CLW",
    "EHF Champions League · Women",
    "5274",
    "handball",
    "https://r2.thesportsdb.com/images/media/league/badge/i8rtav1650475147.png",
    "https://www.eurohandball.com/",
  ],
  [
    "HANDBALL_BUNDESLIGA",
    "Handball Bundesliga",
    "4533",
    "handball",
    "https://r2.thesportsdb.com/images/media/league/badge/yt21x11783630443.png",
    "https://www.daikin-hbl.de/",
  ],
  [
    "ASOBAL",
    "Liga ASOBAL",
    "4534",
    "handball",
    "https://r2.thesportsdb.com/images/media/league/badge/gktgiq1568314160.png",
    "https://asobal.es/",
  ],
  [
    "BWF",
    "BWF World Tour",
    "5646",
    "badminton",
    "https://r2.thesportsdb.com/images/media/league/badge/d5xvqq1750423289.png",
    "https://bwfworldtour.bwfbadminton.com/",
  ],
  [
    "WTT",
    "World Table Tennis",
    "5641",
    "tabletennis",
    "https://r2.thesportsdb.com/images/media/league/badge/fvesg01750422363.png",
    "https://www.worldtabletennis.com/",
  ],
  [
    "WST",
    "World Snooker Tour",
    "4555",
    "snooker",
    "https://r2.thesportsdb.com/images/media/league/badge/0gmkgj1555600537.png",
    "https://www.wst.tv/",
  ],
  [
    "PDC",
    "PDC Darts",
    "4554",
    "darts",
    "https://r2.thesportsdb.com/images/media/league/badge/isf07m1555602216.png",
    "https://www.pdc.tv/",
  ],
  [
    "SUPER_NETBALL",
    "Suncorp Super Netball",
    "4540",
    "netball",
    "https://r2.thesportsdb.com/images/media/league/badge/yik0t61557761303.png",
    "https://supernetball.com.au/",
  ],
  [
    "ANZ_NETBALL",
    "ANZ Premiership",
    "4538",
    "netball",
    "https://r2.thesportsdb.com/images/media/league/badge/7du0cw1555963822.png",
    "https://anzpremiership.co.nz/",
  ],
  [
    "NETBALL_SL",
    "Netball Super League",
    "4539",
    "netball",
    "https://r2.thesportsdb.com/images/media/league/badge/8hccap1741344166.png",
    "https://www.netballsl.com/",
  ],
  [
    "FIH_PRO",
    "FIH Pro League · Men",
    "4558",
    "fieldhockey",
    "https://r2.thesportsdb.com/images/media/league/badge/7f06kq1555843412.png",
    "https://www.fih.hockey/",
  ],
  [
    "EHL",
    "Euro Hockey League",
    "4559",
    "fieldhockey",
    "https://r2.thesportsdb.com/images/media/league/badge/166oni1624293447.png",
    "https://ehlhockey.tv/",
  ],
  [
    "UCI_WT",
    "UCI WorldTour",
    "4465",
    "cycling",
    "https://r2.thesportsdb.com/images/media/league/badge/igahc11535183469.png",
    "https://www.uci.org/",
  ],
  [
    "UCI_WWT",
    "UCI Women’s WorldTour",
    "5312",
    "cycling",
    "https://r2.thesportsdb.com/images/media/league/badge/ozlln81659718492.png",
    "https://www.uci.org/",
  ],
  [
    "UCI_PRO",
    "UCI ProSeries",
    "5330",
    "cycling",
    "https://r2.thesportsdb.com/images/media/league/badge/9dyjmo1660817884.png",
    "https://www.uci.org/",
  ],
  [
    "FIS_ALPINE",
    "FIS Alpine Ski World Cup",
    "5625",
    "winter",
    "https://r2.thesportsdb.com/images/media/league/badge/hx5vbc1763343471.png",
    "https://www.fis-ski.com/",
  ],
  [
    "FIS_CROSSCOUNTRY",
    "FIS Cross-Country World Cup",
    "5722",
    "winter",
    "https://r2.thesportsdb.com/images/media/league/badge/rjr0sa1786630384.png",
    "https://www.fis-ski.com/",
  ],
  [
    "FIS_JUMPING",
    "FIS Ski Jumping World Cup",
    "5724",
    "winter",
    "https://r2.thesportsdb.com/images/media/league/badge/wg35jj1763342530.png",
    "https://www.fis-ski.com/",
  ],
  [
    "IBU",
    "Biathlon World Cup",
    "5342",
    "winter",
    "https://r2.thesportsdb.com/images/media/league/badge/1wi95j1672319601.png",
    "https://www.biathlonworld.com/",
  ],
  [
    "DIAMOND_LEAGUE",
    "Diamond League",
    "5282",
    "athletics",
    "https://r2.thesportsdb.com/images/media/league/badge/7d5xlh1650475438.png",
    "https://www.diamondleague.com/",
  ],
  [
    "WORLD_ATHLETICS",
    "World Athletics Championships",
    "5007",
    "athletics",
    "https://r2.thesportsdb.com/images/media/league/badge/b3tgs91749840167.png",
    "https://worldathletics.org/",
  ],
  [
    "WORLD_ATHLETICS_INDOOR",
    "World Athletics Indoor Championships",
    "5283",
    "athletics",
    "https://r2.thesportsdb.com/images/media/league/badge/1uq5711774008439.png",
    "https://worldathletics.org/",
  ],
] as const;

export const ADDITIONAL_LEAGUES: AdditionalSportsLeague[] = [
  ...calendars.map(([key, label, path, group, logo, officialWebsite]) => ({
    key,
    tag: key,
    label,
    labelEn: label,
    path,
    group,
    logo,
    officialWebsite,
    coverage: "schedule" as const,
  })),
  {
    key: "NCAAW_VB",
    tag: "NCAAW_VB",
    label: "NCAA Women's Volleyball",
    labelEn: "NCAA Women's Volleyball",
    path: "volleyball/womens-college-volleyball",
    group: "volleyball",
    logo: "https://a.espncdn.com/combiner/i?img=/redesign/assets/img/icons/sports-volleyball-solid.png",
    officialWebsite: "https://www.ncaa.com/sports/volleyball-women/d1",
    coverage: "scoreboard",
  },
  {
    key: "NCAAM_VB",
    tag: "NCAAM_VB",
    label: "NCAA Men's Volleyball",
    labelEn: "NCAA Men's Volleyball",
    path: "volleyball/mens-college-volleyball",
    group: "volleyball",
    logo: "https://a.espncdn.com/combiner/i?img=/redesign/assets/img/icons/sports-volleyball-solid.png",
    officialWebsite: "https://www.ncaa.com/sports/volleyball-men/nc",
    coverage: "scoreboard",
  },
  {
    key: "NCAA_FIELDHOCKEY",
    tag: "NCAA_FIELDHOCKEY",
    label: "NCAA Women's Field Hockey",
    labelEn: "NCAA Women's Field Hockey",
    path: "field-hockey/womens-college-field-hockey",
    group: "fieldhockey",
    logo: "https://a.espncdn.com/combiner/i?img=/redesign/assets/img/icons/ESPN-icon-field-hockey.png",
    officialWebsite: "https://www.ncaa.com/sports/fieldhockey/d1",
    coverage: "scoreboard",
  },
  {
    key: "NCAA_SOFTBALL",
    tag: "NCAA_SOFTBALL",
    label: "NCAA Softball",
    labelEn: "NCAA Softball",
    path: "baseball/college-softball",
    group: "softball",
    logo: "https://a.espncdn.com/i/espn/misc_logos/500/ncaa_womens_softball.png",
    officialWebsite: "https://www.ncaa.com/sports/softball/d1",
    coverage: "scoreboard",
  },
];

export const ADDITIONAL_GROUPS: LeagueGroupDef[] = [
  { key: "volleyball", label: "Volleyball", labelEn: "Volleyball", icon: "🏐" },
  { key: "handball", label: "Handball", labelEn: "Handball", icon: "🤾" },
  { key: "badminton", label: "Badminton", labelEn: "Badminton", icon: "🏸" },
  {
    key: "tabletennis",
    label: "Table tennis",
    labelEn: "Table tennis",
    icon: "🏓",
  },
  { key: "snooker", label: "Snooker", labelEn: "Snooker", icon: "🎱" },
  { key: "darts", label: "Darts", labelEn: "Darts", icon: "🎯" },
  { key: "netball", label: "Netball", labelEn: "Netball", icon: "🏐" },
  {
    key: "fieldhockey",
    label: "Field hockey",
    labelEn: "Field hockey",
    icon: "🏑",
  },
  { key: "cycling", label: "Cycling", labelEn: "Cycling", icon: "🚴" },
  {
    key: "winter",
    label: "Winter sports",
    labelEn: "Winter sports",
    icon: "⛷",
  },
  { key: "athletics", label: "Athletics", labelEn: "Athletics", icon: "🏃" },
  { key: "softball", label: "Softball", labelEn: "Softball", icon: "🥎" },
];

export function additionalSportOfficialWebsite(tag: string): string | undefined {
  return ADDITIONAL_LEAGUES.find((league) => league.tag === tag)?.officialWebsite;
}
