import type { LeagueDef } from "./espn-types";

export type ExpandedSportsLeague = LeagueDef & {
  officialWebsite: string;
  /** Calendar/final-result coverage only; the free feed is not a live scoreboard. */
  coverage: "schedule";
};

/**
 * Provider IDs, badges, and upcoming-event responses checked on 2026-09-14;
 * competition identities and official websites checked against their own sites.
 * These are TheSportsDB v1 calendars consumed by the existing numeric-path adapter.
 * The public key's next-league responses returned one event per league in this audit,
 * and catalog searches were capped at five results. Do not imply a complete season
 * or live score coverage. Fetch selected competitions on demand, not all at startup.
 */
export const EXPANDED_SPORTS_LEAGUES: ExpandedSportsLeague[] = [
  {
    key: "AHL",
    label: "American Hockey League",
    labelEn: "American Hockey League",
    tag: "AHL",
    path: "4738",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/bm25ej1582197507.png",
    group: "hockey",
    officialWebsite: "https://theahl.com/",
    coverage: "schedule",
  },
  {
    key: "KHL",
    label: "Kontinental Hockey League",
    labelEn: "Kontinental Hockey League",
    tag: "KHL",
    path: "4920",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/tfmf8l1615492008.png",
    group: "hockey",
    officialWebsite: "https://en.khl.ru/",
    coverage: "schedule",
  },
  {
    key: "SHL",
    label: "Swedish Hockey League",
    labelEn: "Swedish Hockey League",
    tag: "SHL",
    path: "4419",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/3q8qpc1787927189.png",
    group: "hockey",
    officialWebsite: "https://www.shl.se/",
    coverage: "schedule",
  },
  {
    key: "LIIGA",
    label: "Finnish Liiga",
    labelEn: "Finnish Liiga",
    tag: "LIIGA",
    path: "4931",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/thj2p31780638296.png",
    group: "hockey",
    officialWebsite: "https://www.liiga.fi/fi",
    coverage: "schedule",
  },
  {
    key: "DEL",
    label: "Deutsche Eishockey Liga",
    labelEn: "Deutsche Eishockey Liga",
    tag: "DEL",
    path: "4925",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/ttrhds1615493883.png",
    group: "hockey",
    officialWebsite: "https://www.penny-del.org/",
    coverage: "schedule",
  },
  {
    key: "SDHL",
    label: "Swedish Women's Hockey League",
    labelEn: "Swedish Women's Hockey League",
    tag: "SDHL",
    path: "5158",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/iagjdj1644535046.png",
    group: "hockey",
    officialWebsite: "https://www.sdhl.se/",
    coverage: "schedule",
  },
  {
    key: "ECHL",
    label: "ECHL",
    labelEn: "ECHL",
    tag: "ECHL",
    path: "4916",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/im9a7w1783325344.png",
    group: "hockey",
    officialWebsite: "https://www.echl.com/",
    coverage: "schedule",
  },
  {
    key: "EUROLEAGUE",
    label: "EuroLeague",
    labelEn: "EuroLeague",
    tag: "EUROLEAGUE",
    path: "4546",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/7xjtuy1554397263.png",
    group: "basketball",
    officialWebsite: "https://www.euroleaguebasketball.net/euroleague/",
    coverage: "schedule",
  },
  {
    key: "EUROCUP",
    label: "EuroCup Basketball",
    labelEn: "EuroCup Basketball",
    tag: "EUROCUP",
    path: "4547",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/w54nor1554757326.png",
    group: "basketball",
    officialWebsite: "https://www.euroleaguebasketball.net/eurocup/",
    coverage: "schedule",
  },
  {
    key: "ACB",
    label: "Liga ACB",
    labelEn: "Liga ACB",
    tag: "ACB",
    path: "4408",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/4n3h6z1572778356.png",
    group: "basketball",
    officialWebsite: "https://www.acb.com/",
    coverage: "schedule",
  },
  {
    key: "BASKET_BBL",
    label: "Basketball Bundesliga",
    labelEn: "Basketball Bundesliga",
    tag: "BASKET_BBL",
    path: "4441",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/ssgkzq1550038219.png",
    group: "basketball",
    officialWebsite: "https://www.easycredit-bbl.de/",
    coverage: "schedule",
  },
  {
    key: "LNB",
    label: "Betclic Elite",
    labelEn: "Betclic Elite",
    tag: "LNB",
    path: "4423",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/60detm1757608684.png",
    group: "basketball",
    officialWebsite: "https://www.lnb.fr/",
    coverage: "schedule",
  },
  {
    key: "WNBL",
    label: "WNBL",
    labelEn: "WNBL",
    tag: "WNBL",
    path: "5113",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/hnate81749406441.png",
    group: "basketball",
    officialWebsite: "https://www.wnbl.com.au/",
    coverage: "schedule",
  },
  {
    key: "LF_ENDESA",
    label: "Liga Femenina Endesa",
    labelEn: "Liga Femenina Endesa",
    tag: "LF_ENDESA",
    path: "5486",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/igl7v11721543579.png",
    group: "basketball",
    officialWebsite: "https://www.lfendesa.es/inicio.aspx",
    coverage: "schedule",
  },
  {
    key: "LFB",
    label: "La Boulangère Wonderligue",
    labelEn: "La Boulangère Wonderligue",
    tag: "LFB",
    path: "5623",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/o5r1we1746284587.png",
    group: "basketball",
    officialWebsite: "https://basketlfb.com/laboulangerewonderligue",
    coverage: "schedule",
  },
  {
    key: "NRL",
    label: "National Rugby League",
    labelEn: "National Rugby League",
    tag: "NRL",
    path: "4416",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/g5ocbs1777721333.png",
    group: "rugby",
    officialWebsite: "https://www.nrl.com/",
    coverage: "schedule",
  },
  {
    key: "PREM_RUGBY",
    label: "Premiership Rugby",
    labelEn: "Premiership Rugby",
    tag: "PREM_RUGBY",
    path: "4414",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/r59qxy1755025703.png",
    group: "rugby",
    officialWebsite: "https://www.premiershiprugby.com/",
    coverage: "schedule",
  },
  {
    key: "PROD2",
    label: "Pro D2",
    labelEn: "Pro D2",
    tag: "PROD2",
    path: "5172",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/ng4ixj1645178002.png",
    group: "rugby",
    officialWebsite: "https://www.lnr.fr/rugby-pro-d2",
    coverage: "schedule",
  },
  {
    key: "RUGBY_CHAMPIONS_CUP",
    label: "European Rugby Champions Cup",
    labelEn: "European Rugby Champions Cup",
    tag: "RUGBY_CHAMPIONS_CUP",
    path: "4550",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/kohne11716546580.png",
    group: "rugby",
    officialWebsite: "https://www.epcrugby.com/",
    coverage: "schedule",
  },
  {
    key: "RUGBY_CHALLENGE_CUP",
    label: "European Rugby Challenge Cup",
    labelEn: "European Rugby Challenge Cup",
    tag: "RUGBY_CHALLENGE_CUP",
    path: "5418",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/ewua6c1716755405.png",
    group: "rugby",
    officialWebsite: "https://www.epcrugby.com/",
    coverage: "schedule",
  },
];
