import type { SportsGame } from "./espn-types";

export type RacingVenue = {
  id: string;
  name: string;
  sourceName: "NASCAR" | "INDYCAR";
  map?: string;
  outline?: string;
  logo?: string;
  photo?: string;
  sourceUrl: string;
  mapSourceUrl?: string;
  photoSourceUrl?: string;
  website?: string;
  tickets?: string;
  length?: string;
  turns?: number;
  location?: string;
  layout: "oval" | "road" | "street";
  season?: number;
};
type VenueRecord = RacingVenue & {
  aliases: string[];
  leagues: ("nascar" | "indy")[];
};
export type RacingVenueQuery = {
  league: string;
  name?: string;
  venue?: string;
  context?: Pick<NonNullable<SportsGame["context"]>, "name" | "venue">;
  startMs?: number;
  trackId?: string | number;
};

/**
 * Official publisher metadata verified September 2026. No live car coordinates.
 * NASCAR track_image is the published track diagram; track photos are separately
 * sourced from the official ticket/camping pages. Provider placeholder outlines
 * for other tracks (111.png and North Wilkesboro's copied IRP map) are excluded.
 * INDYCAR maps are layout-specific 2026 event maps, including both IMS layouts.
 */
export const RACING_VENUES: readonly VenueRecord[] = [
  {
    id: "nascar-4",
    sourceName: "NASCAR",
    name: "Darlington Raceway",
    aliases: ["Darlington"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/4.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2020/12/21/darlington.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.darlingtonraceway.com/",
    tickets: "https://www.darlingtonraceway.com/event-calendar/",
    length: "1.366 mi",
    turns: 4,
    location: "Darlington, SC",
    layout: "oval",
  },
  {
    id: "nascar-14",
    sourceName: "NASCAR",
    name: "Bristol Motor Speedway",
    aliases: ["Bristol"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/14.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/03/23/61ee2085de545314e374b7248e62dcec.jpg",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.bristolmotorspeedway.com/",
    tickets: "https://www.bristolmotorspeedway.com/tickets/food-city-dirt-race/",
    length: "0.533 mi",
    turns: 4,
    location: "Bristol, TN",
    layout: "oval",
  },
  {
    id: "nascar-22",
    sourceName: "NASCAR",
    name: "Martinsville Speedway",
    aliases: ["Martinsville"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/22.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/11/04/MartinsvilleSpeedway.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.martinsvillespeedway.com/",
    tickets: "https://www.martinsvillespeedway.com/event-calendar/",
    length: "0.526 mi",
    turns: 4,
    location: "Ridgeway, VA",
    layout: "oval",
  },
  {
    id: "nascar-26",
    sourceName: "NASCAR",
    name: "Richmond Raceway",
    aliases: ["Richmond"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/25/26.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/02/22/OPT-RR_Primary-Vert_OnBlk_RGB.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.richmondraceway.com/",
    tickets: "https://www.richmondraceway.com/calendar/",
    length: "0.75 mi",
    turns: 4,
    location: "Richmond, VA",
    layout: "oval",
  },
  {
    id: "nascar-39",
    sourceName: "NASCAR",
    name: "Chicagoland Speedway",
    aliases: ["Chicagoland"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2025/08/16/CLS_TrackShape.jpg",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2026/01/13/CLS_White_Wordmark_501x121.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.chicagolandspeedway.com/",
    tickets: "https://www.chicagolandspeedway.com/events/nascar-cup-series/",
    length: "1.5 mi",
    turns: 4,
    location: "Joliet, IL",
    layout: "oval",
  },
  {
    id: "nascar-40",
    sourceName: "NASCAR",
    name: "Homestead-Miami Speedway",
    aliases: ["Homestead Miami Speedway", "Homestead"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/40.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2022/10/20/LightLogo-330x79-1.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.homesteadmiamispeedway.com/",
    tickets: "https://www.homesteadmiamispeedway.com/calendar/",
    length: "1.5 mi",
    turns: 4,
    location: "Homestead, FL",
    layout: "oval",
  },
  {
    id: "nascar-41",
    sourceName: "NASCAR",
    name: "Kansas Speedway",
    aliases: ["Kansas"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/41.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2024/01/23/Kansas-Speedway-New-Logo-on-Dark-1.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.kansasspeedway.com/",
    tickets: "https://www.kansasspeedway.com/calendar/",
    length: "1.5 mi",
    turns: 4,
    location: "Kansas City, KS",
    layout: "oval",
  },
  {
    id: "nascar-42",
    sourceName: "NASCAR",
    name: "Las Vegas Motor Speedway",
    aliases: ["Las Vegas"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/42.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/03/01/lvms.jpg",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.lvms.com/",
    tickets: "https://www.lvms.com/tickets/",
    length: "1.5 mi",
    turns: 4,
    location: "Las Vegas, NV",
    layout: "oval",
  },
  {
    id: "nascar-43",
    sourceName: "NASCAR",
    name: "Texas Motor Speedway",
    aliases: ["Texas"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/25/43.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/10/12/texas-motor-speedway.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.texasmotorspeedway.com/",
    tickets: "https://www.texasmotorspeedway.com/events/",
    length: "1.5 mi",
    turns: 4,
    location: "Fort Worth, TX",
    layout: "oval",
  },
  {
    id: "nascar-82",
    sourceName: "NASCAR",
    name: "Talladega Superspeedway",
    aliases: ["Talladega"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/25/82.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2024/02/07/Talladega-Website-Rebrand-header.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.talladegasuperspeedway.com/",
    tickets: "https://www.talladegasuperspeedway.com/fall-nascar-cup-ticket-options/",
    length: "2.66 mi",
    turns: 4,
    location: "Talladega, AL",
    layout: "oval",
  },
  {
    id: "nascar-84",
    sourceName: "NASCAR",
    name: "Phoenix Raceway",
    aliases: ["ISM Raceway", "Phoenix International Raceway", "Phoenix"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/84.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2022/03/07/PR-Logo-3C-Horizontal.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.phoenixraceway.com",
    tickets: "https://www.phoenixraceway.com/schedule/",
    length: "1 mi",
    turns: 4,
    location: "Avondale, AZ",
    layout: "oval",
  },
  {
    id: "nascar-103",
    sourceName: "NASCAR",
    name: "Dover Motor Speedway",
    aliases: ["Dover International Speedway", "Dover"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/103.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2022/04/21/DMS_330x132_Header.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.doverspeedway.com/",
    tickets: "https://www.dovermotorspeedway.com/events/nascar-all-star-race/",
    length: "1 mi",
    turns: 4,
    location: "Dover, DE",
    layout: "oval",
  },
  {
    id: "nascar-105",
    sourceName: "NASCAR",
    name: "Daytona International Speedway",
    aliases: ["Daytona", "Daytona 500"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/07/02/105-1.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2022/02/17/DIS-generic.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.daytonainternationalspeedway.com/",
    tickets: "https://www.daytonainternationalspeedway.com/event-calendar/",
    length: "2.5 mi",
    turns: 4,
    location: "Daytona Beach, FL",
    layout: "oval",
  },
  {
    id: "nascar-111",
    sourceName: "NASCAR",
    name: "EchoPark Speedway",
    aliases: ["Atlanta Motor Speedway", "Atlanta", "Echo Park Speedway"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/111.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/06/04/echopark-logo350x265.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.echoparkspeedway.com/",
    tickets: "https://www.echoparkspeedway.com/events/",
    length: "1.54 mi",
    turns: 4,
    location: "Hampton, GA",
    layout: "oval",
  },
  {
    id: "nascar-123",
    sourceName: "NASCAR",
    name: "Indianapolis Motor Speedway",
    aliases: ["Indianapolis Oval", "Brickyard 400"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/123.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/12/09/123-light.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.indianapolismotorspeedway.com/",
    tickets:
      "https://www.indianapolismotorspeedway.com/events/brickyard/buy-tickets/brickyard-renew",
    length: "2.5 mi",
    turns: 4,
    location: "Speedway, IN",
    layout: "oval",
  },
  {
    id: "nascar-133",
    sourceName: "NASCAR",
    name: "Michigan International Speedway",
    aliases: ["Michigan"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/133.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2023/08/01/NASCAR_MichiganSpdwy_OnLight_RGB.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.mispeedway.com/",
    tickets: "https://www.mispeedway.com/schedule/",
    length: "2 mi",
    turns: 4,
    location: "Brooklyn, MI",
    layout: "oval",
  },
  {
    id: "nascar-138",
    sourceName: "NASCAR",
    name: "New Hampshire Motor Speedway",
    aliases: ["New Hampshire"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/25/138.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2024/06/04/NHMS_TrackLogo2.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.nhms.com/",
    tickets: "https://www.nhms.com/events/nascar-cup-series/tickets/",
    length: "1.058 mi",
    turns: 4,
    location: "Loudon, NH",
    layout: "oval",
  },
  {
    id: "nascar-157",
    sourceName: "NASCAR",
    name: "Watkins Glen International",
    aliases: ["Watkins Glen"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/25/157.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/11/04/watkins-glen-logo.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.theglen.com/",
    tickets: "https://www.theglen.com/schedule/",
    length: "2.45 mi",
    turns: 8,
    location: "Watkins Glen, NY",
    layout: "road",
  },
  {
    id: "nascar-162",
    sourceName: "NASCAR",
    name: "Charlotte Motor Speedway",
    aliases: ["Charlotte Oval", "Charlotte"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/162.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2024/06/20/Charlotte-Motor-Speedway.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.charlottemotorspeedway.com/",
    tickets: "https://www.charlottemotorspeedway.com/tickets/",
    length: "1.5 mi",
    turns: 4,
    location: "Concord, NC",
    layout: "oval",
  },
  {
    id: "nascar-206",
    sourceName: "NASCAR",
    name: "Iowa Speedway",
    aliases: ["Iowa"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2024/04/12/IAS.jpg",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/07/28/IOWA_Speedway.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.iowaspeedway.com/",
    tickets: "https://www.iowaspeedway.com/events/summer-cup-series-race/",
    length: "0.875 mi",
    location: "Newton, IA",
    layout: "oval",
  },
  {
    id: "nascar-198",
    sourceName: "NASCAR",
    name: "Pocono Raceway",
    aliases: ["Pocono"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/25/198.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/21/Pocono-Raceway-Marketing-Logo.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.poconoraceway.com/",
    tickets: "https://www.poconoraceway.com/ticket/nascar-tickets",
    length: "2.5 mi",
    turns: 3,
    location: "Long Pond, PA",
    layout: "oval",
  },
  {
    id: "nascar-45",
    sourceName: "NASCAR",
    name: "World Wide Technology Raceway",
    aliases: [
      "Gateway Motorsports Park",
      "Gateway International Raceway",
      "World Wide Technology Raceway at Gateway",
      "WWTR",
      "Gateway",
    ],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/29/45.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/02/24/WWTR_Logo_White2025.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.wwtraceway.com/",
    tickets: "https://wwtraceway.com/2025playoffsenjoyil300/",
    length: "1.25 mi",
    turns: 4,
    location: "Madison, IL",
    layout: "oval",
  },
  {
    id: "nascar-210",
    sourceName: "NASCAR",
    name: "Charlotte Motor Speedway Roval",
    aliases: ["Charlotte Roval", "Charlotte Motor Speedway Road Course", "Roval"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/210.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/10/05/Charlotte-Logo.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.charlottemotorspeedway.com/",
    tickets: "https://www.charlottemotorspeedway.com/tickets/",
    length: "2.32 mi",
    turns: 17,
    location: "Concord, NC",
    layout: "road",
  },
  {
    id: "nascar-214",
    sourceName: "NASCAR",
    name: "Circuit of The Americas",
    aliases: ["COTA"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2026/02/25/214.svg",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/02/25/2025_NASCAR_Cota.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.nascaratcota.com/",
    tickets: "https://www.nascaratcota.com/events/echopark-automotive-grand-prix/tickets/",
    length: "2.4 mi",
    location: "Austin, TX",
    layout: "road",
  },
  {
    id: "nascar-52",
    sourceName: "NASCAR",
    name: "Nashville Superspeedway",
    aliases: ["Nashville"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/24/52.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2024/06/04/NashvilleSuperSpeedway.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.nashvillesuperspeedway.com/",
    tickets: "https://www.nashvillesuperspeedway.com",
    length: "1.333 mi",
    turns: 4,
    location: "Lebanon, TN",
    layout: "oval",
  },
  {
    id: "nascar-204",
    sourceName: "NASCAR",
    name: "Portland International Raceway",
    aliases: [],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/10/07/204.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2024/06/17/PIR.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://portlandraceway.com/",
    length: "1.9 mi",
    location: "Portland, OR",
    layout: "road",
  },
  {
    id: "nascar-47",
    sourceName: "NASCAR",
    name: "Lucas Oil Indianapolis Raceway Park",
    aliases: ["Indianapolis Raceway Park", "Lucas Oil Raceway", "IRP"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/10/07/47.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/12/08/LOIRP-FINAL.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://raceirp.com/",
    tickets: "https://nhra.evenue.net/promotions/NTS",
    length: "0.686 mi",
    location: "Indianapolis, IN",
    layout: "oval",
  },
  {
    id: "nascar-218",
    sourceName: "NASCAR",
    name: "Chicago Street Race",
    aliases: [],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2023/04/14/218.svg",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2024/12/04/2025_NASCAR_Chicago.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.nascarchicago.com",
    length: "2.2 mi",
    location: "Chicago, IL",
    layout: "road",
  },
  {
    id: "nascar-177",
    sourceName: "NASCAR",
    name: "North Wilkesboro Speedway",
    aliases: ["North Wilkesboro"],
    leagues: ["nascar"],
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2022/09/14/North_Wilkesboro_Speedway.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.northwilkesborospeedway.com/",
    tickets:
      "https://www.northwilkesborospeedway.com/events/window-world-400/tickets/#weekendticketpackage",
    length: "0.625 mi",
    turns: 4,
    location: "North Wilkesboro, NC",
    layout: "oval",
  },
  {
    id: "nascar-51",
    sourceName: "NASCAR",
    name: "The Milwaukee Mile",
    aliases: [],
    leagues: ["nascar"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Milwaukee_TrackMap.jpg",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Milwaukee-Race1",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2023/08/23/MKE_Mile_4C.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://savethemile.org/",
    length: "1.015 mi",
    location: "West Allis, WI",
    layout: "oval",
  },
  {
    id: "nascar-75",
    sourceName: "NASCAR",
    name: "Autódromo Hermanos Rodríguez",
    aliases: [],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2024/09/06/75.svg",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/03/26/NASCAR-Mexico_Primary_4C-2_OPTIMIZED.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://nascarmexico.com/?LANG=LANG_EN",
    length: "2.674 mi",
    location: "Mexico City, Mexico",
    layout: "road",
  },
  {
    id: "nascar-1001",
    sourceName: "NASCAR",
    name: "Sebring International Raceway",
    aliases: [],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/11/05/SEBRING_1346x916-350x238-1.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/01/15/Sebring-International-Raceway-_-Iracing_.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.sebringraceway.com/",
    tickets: "https://www.sebringraceway.com/events/mobil-1-twelve-hours-of-sebring-4/",
    length: "3.74 mi",
    location: "Sebring, FL",
    layout: "road",
  },
  {
    id: "nascar-220",
    sourceName: "NASCAR",
    name: "Lime Rock Park",
    aliases: [],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2024/09/06/220.svg",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/11/04/COTA-logo-image.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://limerock.com/",
    tickets: "https://limerock.com/tickets/",
    length: "1.53 mi",
    location: "Lakeville, CT",
    layout: "road",
  },
  {
    id: "nascar-175",
    sourceName: "NASCAR",
    name: "Rockingham Speedway",
    aliases: ["Rockingham"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2025/12/09/RockinghamShape.jpg",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/02/27/Rock-logo-gray.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://racetherock.com/",
    tickets: "https://racetherock.com/tickets/",
    length: "1.017 mi",
    location: "Rockingham, NC",
    layout: "oval",
  },
  {
    id: "nascar-1002",
    sourceName: "NASCAR",
    name: "Michelin Raceway Road Atlanta",
    aliases: [],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2021/11/05/RoadAtlanta_1346x916-350x238-1.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/11/05/MRRA_300XY.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.roadatlanta.com/",
    tickets: "https://michelinracewayroadatlanta.com/fan-guide/fan-experience/purchasing-tickets",
    length: "2.54 mi",
    turns: 12,
    location: "Braselton, GA",
    layout: "road",
  },
  {
    id: "nascar-159",
    sourceName: "NASCAR",
    name: "Bowman Gray Stadium",
    aliases: ["Bowman Gray"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2024/09/11/159.svg",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/01/02/NASCAR_CLASH_onDARKApp.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.bowmangrayracing.com/",
    tickets: "https://www.nascarclash.com/events/nascar-clash/",
    length: "0.25 mi",
    turns: 4,
    location: "Winston Salem, NC",
    layout: "oval",
  },
  {
    id: "nascar-221",
    sourceName: "NASCAR",
    name: "Naval Base Coronado",
    aliases: ["NASCAR San Diego", "San Diego Street Course", "San Diego", "Coronado"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2026/02/25/221.svg",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/09/03/NASCAR_SD.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.nascarsandiego.com/",
    tickets: "https://www.nascarsandiego.com/events/nascar-cup-series/",
    length: "3.4 mi",
    location: "San Diego, CA",
    layout: "street",
  },
  {
    id: "nascar-222",
    sourceName: "NASCAR",
    name: "Grand Prix of St. Petersburg",
    aliases: ["St. Petersburg", "Streets of St. Petersburg"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2026/02/25/222.svg",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2025/01/02/NASCAR_CLASH_onDARKApp.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.gpstpete.com/",
    tickets: "https://www.gpstpete.com/tickets/pricing",
    length: "1.8 mi",
    location: "St. Petersburg, FL",
    layout: "street",
  },
  {
    id: "nascar-99",
    sourceName: "NASCAR",
    name: "Sonoma Raceway",
    aliases: ["Sonoma"],
    leagues: ["nascar"],
    map: "https://www.nascar.com/wp-content/uploads/sites/7/2022/01/12/Sonoma.png",
    logo: "https://www.nascar.com/wp-content/uploads/sites/7/2021/06/01/sonoma_raceway_161.png",
    sourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    mapSourceUrl: "https://cf.nascar.com/cacher/tracks.json",
    website: "https://www.sonomaraceway.com/",
    tickets: "https://www.sonomaraceway.com/tickets/",
    length: "1.99 mi",
    turns: 10,
    location: "Sonoma, CA",
    layout: "road",
  },
  {
    id: "indy-st-petersburg",
    sourceName: "INDYCAR",
    name: "Streets of St. Petersburg",
    aliases: ["St Petersburg", "Grand Prix of St. Petersburg"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/StPete_TrackMap.jpg",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/StPetersburg.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/St-Petersburg",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/St-Petersburg",
    website: "https://www.indycar.com/Schedule/2026/St-Petersburg",
    length: "1.8 mi",
    turns: 14,
    layout: "street",
    season: 2026,
  },
  {
    id: "indy-phoenix",
    sourceName: "INDYCAR",
    name: "Phoenix Raceway",
    aliases: ["Grand Prix of Phoenix", "Phoenix International Raceway"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Phoenix-TrackMap.jpg",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/PhoenixRaceway.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Phoenix",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Phoenix",
    website: "https://www.indycar.com/Schedule/2026/Phoenix",
    length: "1.00 mi",
    layout: "oval",
    season: 2026,
  },
  {
    id: "indy-arlington",
    sourceName: "INDYCAR",
    name: "Streets of Arlington",
    aliases: ["Grand Prix of Arlington"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Arlington_TrackMap.jpg",
    outline: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/Arlington.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Arlington",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Arlington",
    website: "https://www.indycar.com/Schedule/2026/Arlington",
    length: "2.73 mi",
    layout: "street",
    season: 2026,
  },
  {
    id: "indy-barber",
    sourceName: "INDYCAR",
    name: "Barber Motorsports Park",
    aliases: ["Grand Prix of Alabama", "Alabama Grand Prix"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Barber_TrackMap.png",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/BarberMotorsportsPark.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Barber",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Barber",
    website: "https://www.indycar.com/Schedule/2026/Barber",
    length: "2.3 mi",
    turns: 17,
    layout: "road",
    season: 2026,
  },
  {
    id: "indy-long-beach",
    sourceName: "INDYCAR",
    name: "Streets of Long Beach",
    aliases: ["Grand Prix of Long Beach"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/LongBeach_TrackMap.jpg",
    outline: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/LongBeach.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Long-Beach",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Long-Beach",
    website: "https://www.indycar.com/Schedule/2026/Long-Beach",
    length: "1.968 mi",
    turns: 11,
    layout: "street",
    season: 2026,
  },
  {
    id: "indy-indianapolis",
    sourceName: "INDYCAR",
    name: "IMS Road Course",
    aliases: [
      "Indianapolis Motor Speedway Road Course",
      "Grand Prix of Indianapolis Road Course",
      "Grand Prix of Indianapolis",
      "Sonsio Grand Prix",
    ],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Indianapolis-RC-Track-Map.png",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/Indianapolis-RC.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Indianapolis",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Indianapolis",
    website: "https://www.indycar.com/Schedule/2026/Indianapolis",
    length: "2.439 mi",
    turns: 14,
    layout: "road",
    season: 2026,
  },
  {
    id: "indy-indianapolis-500",
    sourceName: "INDYCAR",
    name: "Indianapolis Motor Speedway",
    aliases: ["Indianapolis 500", "Indy 500"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Indianapolis_TrackMap.jpg",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/IndianapolisMotorSpeedway.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Indianapolis-500",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Indianapolis-500",
    website: "https://www.indycar.com/Schedule/2026/Indianapolis-500",
    length: "2.5 mi",
    turns: 4,
    layout: "oval",
    season: 2026,
  },
  {
    id: "indy-wwtr",
    sourceName: "INDYCAR",
    name: "World Wide Technology Raceway",
    aliases: [
      "Grand Prix of Illinois",
      "Gateway Motorsports Park",
      "Gateway International Raceway",
      "World Wide Technology Raceway at Gateway",
      "WWTR",
      "Gateway",
    ],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Gateway_TrackMap.jpg",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/GatewayMotorsportsPark.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/WWTR",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/WWTR",
    website: "https://www.indycar.com/Schedule/2026/WWTR",
    length: "1.25 mi",
    turns: 4,
    layout: "oval",
    season: 2026,
  },
  {
    id: "indy-detroit",
    sourceName: "INDYCAR",
    name: "Streets of Detroit",
    aliases: ["Grand Prix of Detroit"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Detroit_TrackMap.jpg",
    outline: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/Detroit.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Detroit",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Detroit",
    website: "https://www.indycar.com/Schedule/2026/Detroit",
    length: "1.645 mi",
    turns: 9,
    layout: "street",
    season: 2026,
  },
  {
    id: "indy-road-america",
    sourceName: "INDYCAR",
    name: "Road America",
    aliases: ["Grand Prix of Road America"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/RoadAmerica-TrackMap.jpg",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/RoadAmerica.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Road-America",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Road-America",
    website: "https://www.indycar.com/Schedule/2026/Road-America",
    length: "4.014 mi",
    turns: 14,
    layout: "road",
    season: 2026,
  },
  {
    id: "indy-nashville",
    sourceName: "INDYCAR",
    name: "Nashville Superspeedway",
    aliases: ["Grand Prix of Nashville", "Music City Grand Prix"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/NashvilleSS_TrackMap.jpg",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/NashvilleSuperSpeedway.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Nashville",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Nashville",
    website: "https://www.indycar.com/Schedule/2026/Nashville",
    length: "1.33 mi",
    layout: "oval",
    season: 2026,
  },
  {
    id: "indy-mid-ohio",
    sourceName: "INDYCAR",
    name: "Mid-Ohio Sports Car Course",
    aliases: ["Grand Prix of Mid Ohio", "Grand Prix of Mid-Ohio"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/MidOhio_TrackMap.jpg",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/MidOhioSportsCarCourse.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Mid-Ohio",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Mid-Ohio",
    website: "https://www.indycar.com/Schedule/2026/Mid-Ohio",
    length: "2.258 mi",
    turns: 13,
    layout: "road",
    season: 2026,
  },
  {
    id: "indy-washington-dc",
    sourceName: "INDYCAR",
    name: "Streets of Washington",
    aliases: [
      "Grand Prix of Washington D.C.",
      "Grand Prix of Washington DC",
      "Streets of Washington DC",
      "Freedom 250",
    ],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/WashingtonDC-TrackMap.jpg",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/WashingtonDC.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Washington-DC",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Washington-DC",
    website: "https://www.indycar.com/Schedule/2026/Washington-DC",
    length: "1.7 mi",
    layout: "street",
    season: 2026,
  },
  {
    id: "indy-portland",
    sourceName: "INDYCAR",
    name: "Portland International Raceway",
    aliases: ["Grand Prix of Portland"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Portland_TrackMap.jpg",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/PortlandInternationalRaceway.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Portland",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Portland",
    website: "https://www.indycar.com/Schedule/2026/Portland",
    length: "1.967 mi",
    turns: 12,
    layout: "road",
    season: 2026,
  },
  {
    id: "indy-markham",
    sourceName: "INDYCAR",
    name: "Streets of Markham",
    aliases: ["Grand Prix of Ontario", "Grand Prix of Markham"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Markham-TrackMap.jpg",
    outline: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/Markham.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Markham",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Markham",
    website: "https://www.indycar.com/Schedule/2026/Markham",
    length: "2.19 mi",
    turns: 12,
    layout: "street",
    season: 2026,
  },
  {
    id: "indy-laguna-seca",
    sourceName: "INDYCAR",
    name: "WeatherTech Raceway Laguna Seca",
    aliases: ["Laguna Seca", "Grand Prix of Monterey"],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/LagunaSeca_TrackMap.jpg",
    outline: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/LagunaSeca.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Laguna-Seca",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Laguna-Seca",
    website: "https://www.indycar.com/Schedule/2026/Laguna-Seca",
    length: "2.238 mi",
    turns: 11,
    layout: "road",
    season: 2026,
  },
  {
    id: "indy-milwaukee-race1",
    sourceName: "INDYCAR",
    name: "Milwaukee Mile",
    aliases: [
      "Grand Prix of Milwaukee",
      "Grand Prix of Milwaukee Race 1",
      "Grand Prix of Milwaukee Race 2",
      "Milwaukee Mile",
      "The Milwaukee Mile",
    ],
    leagues: ["indy"],
    map: "https://www.indycar.com/-/media/IndyCar/Schedules/TrackMaps/Milwaukee_TrackMap.jpg",
    outline:
      "https://www.indycar.com/-/media/IndyCar/Schedules/TrackOutlines/Black/MilwaukeeMile.png",
    sourceUrl: "https://www.indycar.com/Schedule/2026/Milwaukee-Race1",
    mapSourceUrl: "https://www.indycar.com/Schedule/2026/Milwaukee-Race1",
    website: "https://www.indycar.com/Schedule/2026/Milwaukee-Race1",
    length: "1.015 mi",
    layout: "oval",
    season: 2026,
  },
];

const normalize = (value: string | undefined) =>
  (value ?? "")
    .normalize("NFKD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/([a-z])(\d)/g, "$1 $2")
    .trim();
const contains = (text: string, value: string) => (" " + text + " ").includes(" " + value + " ");
const family = (league: string): "indy" | "nascar" | undefined => {
  const value = normalize(league);
  if (["indy", "indycar", "indycar series", "irl"].includes(value)) return "indy";
  if (
    /^nascar(?: |$)/.test(value) ||
    [
      "xfinity",
      "oreilly",
      "nascarcup",
      "nascarxfinity",
      "nascartrucks",
      "trucks",
      "nxs",
      "ncts",
    ].includes(value)
  )
    return "nascar";
};

/** Conservative venue identity: exact venue first, then unambiguous named-event aliases. */
export function racingVenue(query: RacingVenueQuery): RacingVenue | null {
  const sport = family(query.league);
  if (!sport) return null;
  const venue = normalize(query.venue || query.context?.venue);
  const event = normalize(query.name || query.context?.name);
  if (!venue && !event && query.trackId === undefined) return null;
  const year = query.startMs ? new Date(query.startMs).getFullYear() : undefined;
  if (sport === "indy" && year && year !== 2026) return null;
  const text = [venue, event].join(" ");
  // These events use different layouts at the same facility. Never silently
  // substitute an oval or the new street layout for the explicitly named old one.
  if (/belle isle|nashville street|streets of nashville|toronto|bristol dirt/.test(text))
    return null;
  if (
    sport === "nascar" &&
    /daytona.*road|road.*daytona|indianapolis.*road|road.*indianapolis/.test(text)
  )
    return null;
  const candidates = RACING_VENUES.filter((row) => row.leagues.includes(sport));
  const exactId =
    sport === "nascar" && query.trackId !== undefined
      ? candidates.find((row) => row.id === `nascar-${query.trackId}`)
      : undefined;
  if (exactId) {
    const { aliases: _aliases, leagues: _leagues, ...result } = exactId;
    return result;
  }
  const roadHint = /roval|road course|sonsio|grand prix of indianapolis/.test(text);
  const imsHint = /indianapolis|brickyard|indy 500|ims road/.test(text);
  const ranked = candidates
    .map((row) => {
      if (imsHint && /^(?:indy-indianapolis|nascar-123)/.test(row.id)) {
        if (roadHint !== (row.layout === "road")) return { row, score: 0 };
      }
      if (
        sport === "nascar" &&
        /charlotte|roval/.test(text) &&
        ["nascar-162", "nascar-210"].includes(row.id)
      ) {
        if (roadHint !== (row.layout === "road")) return { row, score: 0 };
      }
      const names = [row.name, ...row.aliases].map(normalize);
      let score = 0;
      for (const name of names) {
        if (venue && venue === name) score = Math.max(score, 1000 + name.length);
        else if (venue && contains(venue, name)) score = Math.max(score, 500 + name.length);
        else if (event && event === name) score = Math.max(score, 400 + name.length);
        else if (
          event &&
          contains(event, name) &&
          (name.includes(" ") || event.endsWith(`at ${name}`) || name === "roval")
        )
          score = Math.max(score, 200 + name.length);
      }
      return { row, score };
    })
    .filter((entry) => entry.score)
    .sort((a, b) => b.score - a.score);
  if (!ranked.length || (ranked[1] && ranked[0].score === ranked[1].score)) return null;
  const { aliases: _aliases, leagues: _leagues, ...result } = ranked[0].row;
  return result;
}
