import type { LeagueDef } from "./espn-types";

export type RegionalLeague = LeagueDef & { officialWebsite: string };

/** Only competitions missing from the established catalog; provider identities stay separate. */
export const REGIONAL_ESPN_LEAGUES: RegionalLeague[] = [
  {
    key: "BRA_SUPERCOPA",
    tag: "BRA_SUPERCOPA",
    label: "كأس السوبر البرازيلي",
    labelEn: "Supercopa Rei",
    path: "soccer/bra.supercopa_do_brazil",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/31h8771766587003.png",
    officialWebsite: "https://www.cbf.com.br/",
  },
  {
    key: "AFC_WOMEN",
    tag: "AFC_WOMEN",
    label: "كأس آسيا للسيدات",
    labelEn: "AFC Women's Asian Cup",
    path: "soccer/afc.w.asian.cup",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/m0scwf1726416187.png",
    officialWebsite: "https://www.the-afc.com/",
  },
  {
    key: "AFCON_WOMEN",
    tag: "AFCON_WOMEN",
    label: "كأس أمم أفريقيا للسيدات",
    labelEn: "Women's Africa Cup of Nations",
    path: "soccer/caf.w.nations",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/cv0ii71707321452.png",
    officialWebsite: "https://www.cafonline.com/",
  },
  {
    key: "AFCON_QUAL",
    tag: "AFCON_QUAL",
    label: "تصفيات كأس أمم أفريقيا",
    labelEn: "Africa Cup of Nations Qualifying",
    path: "soccer/caf.nations_qual",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/e95om51730134202.png",
    officialWebsite: "https://www.cafonline.com/",
  },
];

/** Public schedules and published final scores; these are not a live-score promise. */
export const REGIONAL_DB_LEAGUES: RegionalLeague[] = [
  {
    key: "BRA_SERIEC",
    tag: "BRA_SERIEC",
    label: "الدوري البرازيلي الدرجة الثالثة",
    labelEn: "Brasileirão Série C",
    path: "4625",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/3hp64j1778447225.png",
    officialWebsite: "https://www.cbf.com.br/",
  },
  {
    key: "BRA_SERIED",
    tag: "BRA_SERIED",
    label: "الدوري البرازيلي الدرجة الرابعة",
    labelEn: "Brasileirão Série D",
    path: "5079",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/l50edf1778447349.png",
    officialWebsite: "https://www.cbf.com.br/",
  },
  {
    key: "BRA_WOMEN",
    tag: "BRA_WOMEN",
    label: "البطولة البرازيلية للسيدات",
    labelEn: "Brasileirão Feminino",
    path: "5201",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/es83901752264616.png",
    officialWebsite: "https://www.cbf.com.br/",
  },
  {
    key: "COPA_NORDESTE",
    tag: "COPA_NORDESTE",
    label: "كأس شمال شرق البرازيل",
    labelEn: "Copa do Nordeste",
    path: "5673",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/fhgtm81754479700.png",
    officialWebsite: "https://www.cbf.com.br/",
  },
  {
    key: "COPA_VERDE",
    tag: "COPA_VERDE",
    label: "كأس فيردي",
    labelEn: "Copa Verde",
    path: "5675",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/6v5yt71754490790.png",
    officialWebsite: "https://www.cbf.com.br/",
  },
  {
    key: "BAIANO",
    tag: "BAIANO",
    label: "بطولة باهيا",
    labelEn: "Campeonato Baiano",
    path: "5684",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/ehk7hw1756631450.png",
    officialWebsite: "https://www.fbf.org.br/",
  },
  {
    key: "EGYPT",
    tag: "EGYPT",
    label: "الدوري المصري الممتاز",
    labelEn: "Egyptian Premier League",
    path: "4829",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/v0iz601786057987.png",
    officialWebsite: "https://www.efa.com.eg/",
  },
  {
    key: "MOROCCO",
    tag: "MOROCCO",
    label: "الدوري المغربي",
    labelEn: "Botola Pro",
    path: "4520",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/bhuork1638558615.png",
    officialWebsite: "https://frmf.ma/",
  },
  {
    key: "ALGERIA",
    tag: "ALGERIA",
    label: "الدوري الجزائري",
    labelEn: "Algerian Ligue 1",
    path: "4753",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/ac4ga11714895756.png",
    officialWebsite: "https://www.faf.dz/",
  },
  {
    key: "TUNISIA",
    tag: "TUNISIA",
    label: "الدوري التونسي",
    labelEn: "Tunisian Ligue 1",
    path: "4828",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/qz6ueh1778905288.png",
    officialWebsite: "https://www.ftf.org.tn/",
  },
  {
    key: "UAE",
    tag: "UAE",
    label: "دوري المحترفين الإماراتي",
    labelEn: "UAE Pro League",
    path: "4678",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/95pes01643234997.png",
    officialWebsite: "https://www.uaeproleague.ae/",
  },
  {
    key: "QATAR",
    tag: "QATAR",
    label: "دوري نجوم قطر",
    labelEn: "Qatar Stars League",
    path: "4663",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/hekdan1784606842.png",
    officialWebsite: "https://www.qsl.qa/",
  },
  {
    key: "SAUDI_D1",
    tag: "SAUDI_D1",
    label: "دوري الدرجة الأولى السعودي",
    labelEn: "Saudi First Division",
    path: "5627",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/3tsgu31746325240.png",
    officialWebsite: "https://www.saff.com.sa/",
  },
  {
    key: "SAUDI_SUPERCUP",
    tag: "SAUDI_SUPERCUP",
    label: "كأس السوبر السعودي",
    labelEn: "Saudi Super Cup",
    path: "5650",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/i02vsl1754246325.png",
    officialWebsite: "https://www.saff.com.sa/",
  },
  {
    key: "IRAQ",
    tag: "IRAQ",
    label: "دوري نجوم العراق",
    labelEn: "Iraq Stars League",
    path: "5056",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/qcxorb1724316189.png",
    officialWebsite: "https://ifa.iq/",
  },
  {
    key: "JORDAN",
    tag: "JORDAN",
    label: "الدوري الأردني",
    labelEn: "Jordanian Pro League",
    path: "5055",
    group: "soccer",
    logo: "https://r2.thesportsdb.com/images/media/league/badge/p5gvom1781774834.png",
    officialWebsite: "https://www.jfa.jo/",
  },
];

/** Names and abbreviations observed in ESPN; use these before the aggregate board label fallback. */
export const REGIONAL_SOCCER_ALIASES: Record<string, string> = {
  "Brazilian Serie A": "BRASILEIRAO",
  "Brazil Serie A": "BRASILEIRAO",
  "Brazilian Serie B": "BRASILEIRAOB",
  "Brazil Serie B": "BRASILEIRAOB",
  "Copa do Brasil": "COPADOBRASIL",
  "Copa do Brazil": "COPADOBRASIL",
  "Brazilian Campeonato Paulista": "PAULISTA",
  "Brazil Paulista": "PAULISTA",
  "Brazilian Campeonato Carioca": "CARIOCA",
  "Brazil Carioca": "CARIOCA",
  "Brazilian Campeonato Mineiro": "MINEIRO",
  "Brazil Mineiro": "MINEIRO",
  "Brazilian Campeonato Gaucho": "GAUCHO",
  "Brazil Gaucho": "GAUCHO",
  "Saudi Pro League": "ROSHN",
  "Saudi King's Cup": "KINGSCUP",
  "AFC Champions League Elite": "ACLE",
  "AFC Champions League Two": "ACL2",
  "CAF Champions League": "CAFCL",
  "CAF Confederation Cup": "CAFCC",
  "Brazilian Supercopa Rei": "BRA_SUPERCOPA",
  "Supercopa Rei": "BRA_SUPERCOPA",
  "AFC Women's Asian Cup": "AFC_WOMEN",
  "Women's Africa Cup of Nations": "AFCON_WOMEN",
  "Africa Cup of Nations Qualifying": "AFCON_QUAL",
  "AFCON Qualifying": "AFCON_QUAL",
};

export const REGIONAL_PORTUGUESE_LABELS: Record<string, string> = {
  BRASILEIRAO: "Brasileirão Série A",
  BRASILEIRAOB: "Brasileirão Série B",
  COPADOBRASIL: "Copa do Brasil",
  PAULISTA: "Campeonato Paulista",
  CARIOCA: "Campeonato Carioca",
  MINEIRO: "Campeonato Mineiro",
  GAUCHO: "Campeonato Gaúcho",
  BRA_SERIEC: "Brasileirão Série C",
  BRA_SERIED: "Brasileirão Série D",
  BRA_WOMEN: "Brasileirão Feminino",
  COPA_NORDESTE: "Copa do Nordeste",
  COPA_VERDE: "Copa Verde",
  BAIANO: "Campeonato Baiano",
  BRA_SUPERCOPA: "Supercopa Rei",
};

export function regionalOfficialWebsite(tag: string): string | undefined {
  return [...REGIONAL_ESPN_LEAGUES, ...REGIONAL_DB_LEAGUES].find((league) => league.tag === tag)
    ?.officialWebsite;
}
